#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Uniaxial.inc\n"
#end
/////////////////////////////////////////////////
//              UNIAXIAL MINERALS              //
/////////////////////////////////////////////////


#declare Abenakiite_Ce_IOR_e_1 = 1.586;
#declare Abenakiite_Ce_IOR_w_1 = 1.589;
#declare Abenakiite_Ce_Birefringence_1 = 0.0030;

#declare Abernathyite_IOR_e_1 = 1.57;
#declare Abernathyite_IOR_w_1 = 1.597;
#declare Abernathyite_Birefringence_1 = 0.0270;

#declare Abhurite_IOR_e_1 = 2.11;
#declare Abhurite_IOR_w_1 = 2.06;
#declare Abhurite_Birefringence_1 = 0.0500;

#declare Acetamide_IOR_e_1 = 1.46;
#declare Acetamide_IOR_w_1 = 1.495;
#declare Acetamide_Birefringence_1 = 0.0350;

#declare Afghanite_IOR_e_1 = 1.529;
#declare Afghanite_IOR_w_1 = 1.523;
#declare Afghanite_Birefringence_1 = 0.0060;

#declare Agardite_Y_IOR_e_1 = 1.782;
#declare Agardite_Y_IOR_w_1 = 1.701;
#declare Agardite_Y_Birefringence_1 = 0.0810;

#declare Akdalaite_IOR_e_1 = 1.741;
#declare Akdalaite_IOR_w_1 = 1.747;
#declare Akdalaite_Birefringence_1 = 0.0060;

#declare Akermanite_IOR_e_1 = 1.64;
#declare Akermanite_IOR_w_1 = 1.632;
#declare Akermanite_Birefringence_1 = 0.0080;

#declare Alarsite_IOR_e_1 = 1.608;
#declare Alarsite_IOR_w_1 = 1.596;
#declare Alarsite_Birefringence_1 = 0.0120;

#declare Alforsite_IOR_e_1 = 1.7;
#declare Alforsite_IOR_w_1 = 1.7;
#declare Alforsite_Birefringence_1 = 0.0000;

#declare Alluaivite_IOR_e_1 = 1.626;
#declare Alluaivite_IOR_w_1 = 1.618;
#declare Alluaivite_Birefringence_1 = 0.0080;

#declare Alunite_IOR_e_1 = 1.592;
#declare Alunite_IOR_w_1 = 1.572;
#declare Alunite_Birefringence_1 = 0.0200;

#declare Amakinite_IOR_e_1 = 1.722;
#declare Amakinite_IOR_w_1 = 1.707;
#declare Amakinite_Birefringence_1 = 0.0150;

#declare Aminoffite_IOR_e_1 = 1.637;
#declare Aminoffite_IOR_w_1 = 1.647;
#declare Aminoffite_Birefringence_1 = 0.0100;

#declare Ammonioalunite_IOR_e_1 = 1.602;
#declare Ammonioalunite_IOR_w_1 = 1.59;
#declare Ammonioalunite_Birefringence_1 = 0.0120;

#declare Ammoniojarosite_IOR_e_1 = 1.75;
#declare Ammoniojarosite_IOR_w_1 = 1.8;
#declare Ammoniojarosite_Birefringence_1 = 0.0500;

#declare Ammonioleucite_IOR_e_1 = 1.518;
#declare Ammonioleucite_IOR_w_1 = 1.518;
#declare Ammonioleucite_Birefringence_1 = 0.0000;

#declare Anatase_IOR_e_1 = 2.488;
#declare Anatase_IOR_w_1 = 2.561;
#declare Anatase_Birefringence_1 = 0.0730;

#declare Ankerite_IOR_e_1 = 1.51;
#declare Ankerite_IOR_e_2 = 1.55;
#declare Ankerite_IOR_w_1 = 1.69;
#declare Ankerite_IOR_w_2 = 1.75;
#declare Ankerite_Birefringence_1 = 0.1800;
#declare Ankerite_Birefringence_2 = 0.2000;

#declare Antarcticite_IOR_e_1 = 1.495;
#declare Antarcticite_IOR_w_1 = 1.55;
#declare Antarcticite_Birefringence_1 = 0.0550;

#declare Apatite_IOR_e_1 = 1.63;
#declare Apatite_IOR_w_1 = 1.633;
#declare Apatite_Birefringence_1 = 0.0030;

#declare Aphthitalite_IOR_e_1 = 1.492;
#declare Aphthitalite_IOR_e_2 = 1.499;
#declare Aphthitalite_IOR_w_1 = 1.487;
#declare Aphthitalite_IOR_w_2 = 1.491;
#declare Aphthitalite_Birefringence_1 = 0.0050;
#declare Aphthitalite_Birefringence_2 = 0.0080;

#declare Apophyllite_IOR_e_1 = 1.537;
#declare Apophyllite_IOR_w_1 = 1.535;
#declare Apophyllite_Birefringence_1 = 0.0020;

#declare Archerite_IOR_e_1 = 1.47;
#declare Archerite_IOR_w_1 = 1.513;
#declare Archerite_Birefringence_1 = 0.0430;

#declare Arctite_IOR_e_1 = 1.577;
#declare Arctite_IOR_w_1 = 1.578;
#declare Arctite_Birefringence_1 = 0.0010;

#declare Argentojarosite_IOR_e_1 = 1.785;
#declare Argentojarosite_IOR_w_1 = 1.882;
#declare Argentojarosite_Birefringence_1 = 0.0970;

#declare Argutite_IOR_e_1 = 2.01;
#declare Argutite_IOR_w_1 = 2.01;
#declare Argutite_Birefringence_1 = 0.0000;

#declare Armangite_IOR_e_1 = 1.99;
#declare Armangite_IOR_w_1 = 2.01;
#declare Armangite_Birefringence_1 = 0.0200;

#declare Arnhemite_IOR_e_1 = 1.503;
#declare Arnhemite_IOR_w_1 = 1.516;
#declare Arnhemite_Birefringence_1 = 0.0130;

#declare Arsenocrandallite_IOR_a_1 = 1.625;
#declare Arsenocrandallite_IOR_b_1 = 1.625;
#declare Arsenocrandallite_Birefringence_1 = 0.0000;

#declare Arsenoflorencite_Ce_IOR_e_1 = 1.745;
#declare Arsenoflorencite_Ce_IOR_w_1 = 1.739;
#declare Arsenoflorencite_Ce_Birefringence_1 = 0.0060;

#declare Arsenoflorencite_La_IOR_e_1 = 1.75;
#declare Arsenoflorencite_La_IOR_w_1 = 1.74;
#declare Arsenoflorencite_La_Birefringence_1 = 0.0100;

#declare Arsenoflorencite_Nd_IOR_e_1 = 1.75;
#declare Arsenoflorencite_Nd_IOR_w_1 = 1.74;
#declare Arsenoflorencite_Nd_Birefringence_1 = 0.0100;

#declare Arsenogorceixite_IOR_e_1 = 1.645;
#declare Arsenogorceixite_IOR_w_1 = 1.645;
#declare Arsenogorceixite_Birefringence_1 = 0.0000;

#declare Arsenogoyazite_IOR_a_1 = 1.64;
#declare Arsenogoyazite_IOR_b_1 = 1.64;
#declare Arsenogoyazite_Birefringence_1 = 0.0000;

#declare Arsenuranospathite_IOR_e_1 = 1.538;
#declare Arsenuranospathite_IOR_w_1 = 1.542;
#declare Arsenuranospathite_Birefringence_1 = 0.0040;

#declare Asbecasite_IOR_e_1 = 1.83;
#declare Asbecasite_IOR_w_1 = 1.86;
#declare Asbecasite_Birefringence_1 = 0.0300;

#declare Ashburtonite_IOR_e_1 = 1.8;
#declare Ashburtonite_IOR_w_1 = 1.786;
#declare Ashburtonite_Birefringence_1 = 0.0140;

#declare Ashcroftine_Ce_IOR_e_1 = 1.545;
#declare Ashcroftine_Ce_IOR_w_1 = 1.536;
#declare Ashcroftine_Ce_Birefringence_1 = 0.0090;

#declare Ashcroftine_Y_IOR_e_1 = 1.545;
#declare Ashcroftine_Y_IOR_w_1 = 1.536;
#declare Ashcroftine_Y_Birefringence_1 = 0.0090;

#declare Ashoverite_IOR_e_1 = 1.639;
#declare Ashoverite_IOR_w_1 = 1.629;
#declare Ashoverite_Birefringence_1 = 0.0100;

#declare Asisite_IOR_e_1 = 2.32;
#declare Asisite_IOR_w_1 = 2.39;
#declare Asisite_Birefringence_1 = 0.0700;

#declare Astrocyanite_Ce_IOR_e_1 = 1.638;
#declare Astrocyanite_Ce_IOR_w_1 = 1.688;
#declare Astrocyanite_Ce_Birefringence_1 = 0.0500;

#declare Atlasovite_IOR_e_1 = 1.776;
#declare Atlasovite_IOR_w_1 = 1.783;
#declare Atlasovite_Birefringence_1 = 0.0070;

#declare Babefphite_IOR_e_1 = 1.632;
#declare Babefphite_IOR_w_1 = 1.629;
#declare Babefphite_Birefringence_1 = 0.0030;

#declare Bandylite_IOR_a_1 = 1.641;
#declare Bandylite_IOR_b_1 = 1.691;
#declare Bandylite_Birefringence_1 = 0.0500;

#declare Baotite_IOR_e_1 = 1.944;

#declare Bararite_IOR_e_1 = 1.391;
#declare Bararite_IOR_w_1 = 1.406;
#declare Bararite_Birefringence_1 = 0.0150;

#declare Barbertonite_IOR_e_1 = 1.529;
#declare Barbertonite_IOR_w_1 = 1.557;
#declare Barbertonite_Birefringence_1 = 0.0280;

#declare Barium_pharmacosiderite_IOR_a_1 = 1.57;
#declare Barium_pharmacosiderite_IOR_b_1 = 1.57;
#declare Barium_pharmacosiderite_Birefringence_1 = 0.0000;

#declare Barium_zinc_alumopharmacosiderite_IOR_e_1 = 1.56;
#declare Barium_zinc_alumopharmacosiderite_IOR_w_1 = 1.572;
#declare Barium_zinc_alumopharmacosiderite_Birefringence_1 = 0.0120;

#declare Barysilite_IOR_e_1 = 2.015;
#declare Barysilite_IOR_w_1 = 2.033;
#declare Barysilite_Birefringence_1 = 0.0180;

#declare Basaluminite_IOR_e_1 = 1.515;
#declare Basaluminite_IOR_e_2 = 1.519;
#declare Basaluminite_IOR_w_1 = 1.515;
#declare Basaluminite_IOR_w_2 = 1.519;
#declare Basaluminite_Birefringence_1 = 0.0000;

#declare Bastnasite_Ce_IOR_e_1 = 1.818;
#declare Bastnasite_Ce_IOR_w_1 = 1.717;
#declare Bastnasite_Ce_Birefringence_1 = 0.1010;

#declare Bastnasite_La_IOR_e_1 = 1.818;
#declare Bastnasite_La_IOR_w_1 = 1.717;
#declare Bastnasite_La_Birefringence_1 = 0.1010;

#declare Bastnasite_Y_IOR_e_1 = 1.818;
#declare Bastnasite_Y_IOR_w_1 = 1.717;
#declare Bastnasite_Y_Birefringence_1 = 0.1010;

#declare Bazirite_IOR_e_1 = 1.685;
#declare Bazirite_IOR_e_2 = 1.691;
#declare Bazirite_IOR_w_1 = 1.6751;
#declare Bazirite_IOR_w_2 = 1.6813;
#declare Bazirite_Birefringence_1 = 0.0097;
#declare Bazirite_Birefringence_2 = 0.0099;

#declare Bazzite_IOR_e_1 = 1.605;
#declare Bazzite_IOR_w_1 = 1.626;
#declare Bazzite_Birefringence_1 = 0.0210;

#declare Beaverite_IOR_e_1 = 1.83;
#declare Beaverite_IOR_w_1 = 1.85;
#declare Beaverite_Birefringence_1 = 0.0200;

#declare Bechererite_IOR_e_1 = 1.611;
#declare Bechererite_IOR_w_1 = 1.705;
#declare Bechererite_Birefringence_1 = 0.0940;

#declare Belkovite_IOR_e_1 = 2.002;
#declare Belkovite_IOR_w_1 = 1.928;
#declare Belkovite_Birefringence_1 = 0.0740;

#declare Bellbergite_IOR_e_1 = 1.507;
#declare Bellbergite_IOR_w_1 = 1.522;
#declare Bellbergite_Birefringence_1 = 0.0150;

#declare Belovite_Ce_IOR_e_1 = 1.64;
#declare Belovite_Ce_IOR_w_1 = 1.66;
#declare Belovite_Ce_Birefringence_1 = 0.0200;

#declare Belovite_La_IOR_e_1 = 1.635;
#declare Belovite_La_IOR_w_1 = 1.653;
#declare Belovite_La_Birefringence_1 = 0.0180;

#declare Benauite_IOR_e_1 = 1.862;
#declare Benauite_IOR_w_1 = 1.872;
#declare Benauite_Birefringence_1 = 0.0100;

#declare Benitoite_IOR_e_1 = 1.804;
#declare Benitoite_IOR_w_1 = 1.757;
#declare Benitoite_Birefringence_1 = 0.0470;

#declare Benstonite_IOR_e_1 = 1.527;
#declare Benstonite_IOR_w_1 = 1.69;
#declare Benstonite_Birefringence_1 = 0.1630;

#declare Bentorite_IOR_e_1 = 1.484;
#declare Bentorite_IOR_w_1 = 1.478;
#declare Bentorite_Birefringence_1 = 0.0060;

#declare Berborite_IOR_e_1 = 1.485;
#declare Berborite_IOR_w_1 = 1.58;
#declare Berborite_Birefringence_1 = 0.0950;

#declare Berezanskite_IOR_e_1 = 1.63;
#declare Berezanskite_IOR_w_1 = 1.635;
#declare Berezanskite_Birefringence_1 = 0.0050;

#declare Berlinite_IOR_e_1 = 1.529;
#declare Berlinite_IOR_w_1 = 1.5235;
#declare Berlinite_Birefringence_1 = 0.0055;

#declare Beryl_IOR_e_1 = 1.564;
#declare Beryl_IOR_e_2 = 1.595;
#declare Beryl_IOR_w_1 = 1.568;
#declare Beryl_IOR_w_2 = 1.602;
#declare Beryl_Birefringence_1 = 0.0040;
#declare Beryl_Birefringence_2 = 0.0070;

#declare Beudantite_IOR_e_1 = 1.943;
#declare Beudantite_IOR_w_1 = 1.957;
#declare Beudantite_Birefringence_1 = 0.0140;

#declare Beyerite_IOR_e_1 = 1.97;
#declare Beyerite_IOR_w_1 = 2.13;
#declare Beyerite_Birefringence_1 = 0.1600;

#declare Biphosphammite_IOR_e_1 = 1.48;
#declare Biphosphammite_IOR_w_1 = 1.525;
#declare Biphosphammite_Birefringence_1 = 0.0450;

#declare Bismite_IOR_e_1 = 1.82;
#declare Bismite_IOR_w_1 = 2;
#declare Bismite_Birefringence_1 = 0.1800;

#declare Bismoclite_IOR_e_1 = 1.91;
#declare Bismoclite_IOR_w_1 = 2.15;
#declare Bismoclite_Birefringence_1 = 0.2400;

#declare Bismutite_IOR_a_1 = 2.12;
#declare Bismutite_IOR_a_2 = 2.15;
#declare Bismutite_IOR_b_1 = 2.12;
#declare Bismutite_IOR_b_2 = 2.3;
#declare Bismutite_Birefringence_1 = 0.1300;
#declare Bismutite_Birefringence_2 = 0.1600;

#declare Blatonite_IOR_e_1 = 1.612;
#declare Blatonite_IOR_w_1 = 1.588;
#declare Blatonite_Birefringence_1 = 0.0240;

#declare Boleite_IOR_e_1 = 2.03;
#declare Boleite_IOR_w_1 = 2.04;
#declare Boleite_Birefringence_1 = 0.0100;

#declare Bottinoite_IOR_e_1 = 1.605;
#declare Bottinoite_IOR_w_1 = 1.6;
#declare Bottinoite_Birefringence_1 = 0.0050;

#declare Braitschite_Ce_IOR_e_1 = 1.647;
#declare Braitschite_Ce_IOR_w_1 = 1.646;
#declare Braitschite_Ce_Birefringence_1 = 0.0010;

#declare Brannockite_IOR_e_1 = 1.566;
#declare Brannockite_IOR_w_1 = 1.567;
#declare Brannockite_Birefringence_1 = 0.0010;

#declare Britholite_Y_IOR_e_1 = 1.728;
#declare Britholite_Y_IOR_w_1 = 1.732;
#declare Britholite_Y_Birefringence_1 = 0.0040;

#declare Brizziite_III_IOR_e_1 = 1.631;
#declare Brizziite_III_IOR_w_1 = 1.84;
#declare Brizziite_III_Birefringence_1 = 0.2090;

#declare Brizziite_VII_IOR_e_1 = 1.631;
#declare Brizziite_VII_IOR_w_1 = 1.84;
#declare Brizziite_VII_Birefringence_1 = 0.2090;

#declare Brockite_IOR_e_1 = 1.695;
#declare Brockite_IOR_w_1 = 1.68;
#declare Brockite_Birefringence_1 = 0.0150;

#declare Bromellite_IOR_e_1 = 1.733;
#declare Bromellite_IOR_w_1 = 1.719;
#declare Bromellite_Birefringence_1 = 0.0140;

#declare Brucite_IOR_e_1 = 1.58;
#declare Brucite_IOR_w_1 = 1.56;
#declare Brucite_Birefringence_1 = 0.0200;

#declare Brugnatellite_IOR_e_1 = 1.51;
#declare Brugnatellite_IOR_w_1 = 1.54;
#declare Brugnatellite_Birefringence_1 = 0.0300;

#declare Buergerite_IOR_e_1 = 1.655;
#declare Buergerite_IOR_w_1 = 1.735;
#declare Buergerite_Birefringence_1 = 0.0800;

#declare Buetschliite_IOR_e_1 = 1.445;
#declare Buetschliite_IOR_w_1 = 1.595;
#declare Buetschliite_Birefringence_1 = 0.1500;

#declare Burbankite_IOR_a_1 = 1.615;
#declare Burbankite_IOR_b_1 = 1.627;
#declare Burbankite_Birefringence_1 = 0.0120;

#declare Burtite_IOR_a_1 = 1.63;
#declare Burtite_IOR_b_1 = 1.633;
#declare Burtite_Birefringence_1 = 0.0030;

#declare Buttgenbachite_IOR_e_1 = 1.752;
#declare Buttgenbachite_IOR_w_1 = 1.738;
#declare Buttgenbachite_Birefringence_1 = 0.0140;

#declare Bystrite_IOR_e_1 = 1.66;
#declare Bystrite_IOR_w_1 = 1.584;
#declare Bystrite_Birefringence_1 = 0.0760;

#declare Bystromite_IOR_b_1 = 1.86;
#declare Bystromite_IOR_b_2 = 1.91;

#declare Cacoxenite_IOR_e_1 = 1.64;
#declare Cacoxenite_IOR_e_2 = 1.65;
#declare Cacoxenite_IOR_w_1 = 1.58;
#declare Cacoxenite_IOR_w_2 = 1.585;
#declare Cacoxenite_Birefringence_1 = 0.0600;
#declare Cacoxenite_Birefringence_2 = 0.0650;

#declare Cahnite_IOR_e_1 = 1.663;
#declare Cahnite_IOR_w_1 = 1.662;
#declare Cahnite_Birefringence_1 = 0.0010;

#declare Calcioburbankite_IOR_e_1 = 1.631;
#declare Calcioburbankite_IOR_w_1 = 1.636;
#declare Calcioburbankite_Birefringence_1 = 0.0050;

#declare Calciohilairite_IOR_e_1 = 1.619;
#declare Calciohilairite_IOR_w_1 = 1.622;
#declare Calciohilairite_Birefringence_1 = 0.0030;

#declare Calcite_IOR_e_1 = 1.486;
#declare Calcite_IOR_w_1 = 1.64;
#declare Calcite_IOR_w_2 = 1.66;
#declare Calcite_Birefringence_1 = 0.1540;
#declare Calcite_Birefringence_2 = 0.1740;

#declare Calciumcatapleiite_IOR_e_1 = 1.639;
#declare Calciumcatapleiite_IOR_w_1 = 1.603;
#declare Calciumcatapleiite_Birefringence_1 = 0.0360;

#declare Calcurmolite_IOR_e_1 = 1.816;
#declare Calcurmolite_IOR_e_2 = 1.827;
#declare Calcurmolite_IOR_w_1 = 1.856;
#declare Calcurmolite_IOR_w_2 = 1.863;
#declare Calcurmolite_Birefringence_1 = 0.0360;
#declare Calcurmolite_Birefringence_2 = 0.0400;

#declare Calomel_IOR_e_1 = 2.65;
#declare Calomel_IOR_w_1 = 1.97;
#declare Calomel_Birefringence_1 = 0.6800;

#declare Calzirtite_IOR_e_1 = 2.3;
#declare Calzirtite_IOR_e_2 = 2.36;
#declare Calzirtite_IOR_w_1 = 2.19;
#declare Calzirtite_IOR_w_2 = 2.27;
#declare Calzirtite_Birefringence_1 = 0.0900;
#declare Calzirtite_Birefringence_2 = 0.1100;

#declare Caminite_IOR_e_1 = 1.532;
#declare Caminite_IOR_w_1 = 1.534;
#declare Caminite_Birefringence_1 = 0.0020;

#declare Cancrinite_IOR_e_1 = 1.495;
#declare Cancrinite_IOR_e_2 = 1.503;
#declare Cancrinite_IOR_w_1 = 1.507;
#declare Cancrinite_IOR_w_2 = 1.528;
#declare Cancrinite_Birefringence_1 = 0.0120;
#declare Cancrinite_Birefringence_2 = 0.0250;

#declare Cancrisilite_IOR_e_1 = 1.49;
#declare Cancrisilite_IOR_w_1 = 1.509;
#declare Cancrisilite_Birefringence_1 = 0.0190;

#declare Cappelenite_Y_IOR_b_1 = 1.76;

#declare Carbonate_fluorapatite_IOR_e_1 = 1.6155;
#declare Carbonate_fluorapatite_IOR_w_1 = 1.6785;
#declare Carbonate_fluorapatite_Birefringence_1 = 0.0630;

#declare Carbonate_hydroxylapatite_IOR_e_1 = 1.598;
#declare Carbonate_hydroxylapatite_IOR_e_2 = 1.619;
#declare Carbonate_hydroxylapatite_IOR_w_1 = 1.603;
#declare Carbonate_hydroxylapatite_IOR_w_2 = 1.628;
#declare Carbonate_hydroxylapatite_Birefringence_1 = 0.0050;
#declare Carbonate_hydroxylapatite_Birefringence_2 = 0.0090;

#declare Caresite_IOR_e_1 = 1.57;
#declare Caresite_IOR_w_1 = 1.599;
#declare Caresite_Birefringence_1 = 0.0290;

#declare Carletonite_IOR_e_1 = 1.517;
#declare Carletonite_IOR_w_1 = 1.521;
#declare Carletonite_Birefringence_1 = 0.0040;

#declare Carlosruizite_IOR_e_1 = 1.642;
#declare Carlosruizite_IOR_w_1 = 1.655;
#declare Carlosruizite_Birefringence_1 = 0.0130;

#declare Carrboydite_IOR_w_1 = 1.54;
#declare Carrboydite_IOR_w_2 = 1.56;

#declare Cassiterite_IOR_e_1 = 2.097;
#declare Cassiterite_IOR_e_2 = 2.1;
#declare Cassiterite_IOR_w_1 = 2;
#declare Cassiterite_IOR_w_2 = 2.006;
#declare Cassiterite_Birefringence_1 = 0.0940;
#declare Cassiterite_Birefringence_2 = 0.0970;

#declare Cerite_Ce_IOR_e_1 = 1.81;
#declare Cerite_Ce_IOR_e_2 = 1.82;
#declare Cerite_Ce_IOR_w_1 = 1.806;
#declare Cerite_Ce_IOR_w_2 = 1.81;
#declare Cerite_Ce_Birefringence_1 = 0.0040;
#declare Cerite_Ce_Birefringence_2 = 0.0100;

#declare Cesanite_IOR_e_1 = 1.564;
#declare Cesanite_IOR_w_1 = 1.57;
#declare Cesanite_Birefringence_1 = 0.0060;

#declare Chadwickite_IOR_e_1 = 1.75;
#declare Chadwickite_IOR_w_1 = 1.84;
#declare Chadwickite_Birefringence_1 = 0.0900;

#declare Chalcophanite_IOR_e_1 = 2.72;
#declare Chalcophanite_IOR_w_1 = 2.72;
#declare Chalcophanite_Birefringence_1 = 0.0000;

#declare Chalcophyllite_IOR_e_1 = 1.552;
#declare Chalcophyllite_IOR_e_2 = 1.575;
#declare Chalcophyllite_IOR_w_1 = 1.618;
#declare Chalcophyllite_IOR_w_2 = 1.632;
#declare Chalcophyllite_Birefringence_1 = 0.0570;
#declare Chalcophyllite_Birefringence_2 = 0.0660;

#declare Changbaiite_IOR_e_1 = 2.485;
#declare Changbaiite_IOR_w_1 = 2.476;
#declare Changbaiite_Birefringence_1 = 0.0090;

#declare Chantalite_IOR_e_1 = 1.642;
#declare Chantalite_IOR_w_1 = 1.653;
#declare Chantalite_Birefringence_1 = 0.0110;

#declare Charlesite_IOR_e_1 = 1.475;
#declare Charlesite_IOR_w_1 = 1.492;
#declare Charlesite_Birefringence_1 = 0.0170;

#declare Charmarite_2H_IOR_e_1 = 1.547;
#declare Charmarite_2H_IOR_w_1 = 1.587;
#declare Charmarite_2H_Birefringence_1 = 0.0400;

#declare Charmarite_3T_IOR_e_1 = 1.547;
#declare Charmarite_3T_IOR_w_1 = 1.587;
#declare Charmarite_3T_Birefringence_1 = 0.0400;

#declare Chayesite_IOR_e_1 = 1.578;
#declare Chayesite_IOR_w_1 = 1.575;
#declare Chayesite_Birefringence_1 = 0.0030;

#declare Chernikovite_IOR_e_1 = 1.569;
#declare Chernikovite_IOR_w_1 = 1.583;
#declare Chernikovite_Birefringence_1 = 0.0140;

#declare Chernovite_Y_IOR_e_1 = 1.879;
#declare Chernovite_Y_IOR_w_1 = 1.783;
#declare Chernovite_Y_Birefringence_1 = 0.0960;

#declare Chiluite_IOR_e_1 = 2.3;
#declare Chiluite_IOR_w_1 = 2.4;
#declare Chiluite_Birefringence_1 = 0.1000;

#declare Chiolite_IOR_e_1 = 1.342;
#declare Chiolite_IOR_w_1 = 1.349;
#declare Chiolite_Birefringence_1 = 0.0070;

#declare Chladniite_IOR_e_1 = 1.6;
#declare Chladniite_IOR_w_1 = 1.62;
#declare Chladniite_Birefringence_1 = 0.0200;

#declare Chloraluminite_IOR_e_1 = 1.507;
#declare Chloraluminite_IOR_w_1 = 1.56;
#declare Chloraluminite_Birefringence_1 = 0.0530;

#declare Chlorartinite_IOR_a_1 = 1.51;
#declare Chlorartinite_IOR_b_1 = 1.51;
#declare Chlorartinite_Birefringence_1 = 0.0000;

#declare Chlormagaluminite_IOR_e_1 = 1.56;
#declare Chlormagaluminite_IOR_w_1 = 1.54;
#declare Chlormagaluminite_Birefringence_1 = 0.0200;

#declare Chlormanganokalite_IOR_e_1 = 1.59;
#declare Chlormanganokalite_IOR_w_1 = 1.59;
#declare Chlormanganokalite_Birefringence_1 = 0.0000;

#declare Chromatite_IOR_e_1 = 1.84;
#declare Chromatite_IOR_e_2 = 1.88;
#declare Chromatite_IOR_w_1 = 1.81;
#declare Chromatite_IOR_w_2 = 1.85;
#declare Chromatite_Birefringence_1 = 0.0300;

#declare Chrombismite_IOR_e_1 = 2.55;
#declare Chrombismite_IOR_w_1 = 2.5;
#declare Chrombismite_Birefringence_1 = 0.0500;

#declare Chromdravite_IOR_e_1 = 1.772;
#declare Chromdravite_IOR_w_1 = 1.778;
#declare Chromdravite_Birefringence_1 = 0.0060;

#declare Chrysocolla_IOR_e_1 = 1.57;
#declare Chrysocolla_IOR_w_1 = 1.46;
#declare Chrysocolla_Birefringence_1 = 0.1380;
#declare Chrysocolla_Birefringence_2 = 0.1750;

#declare Cinnabar_IOR_e_1 = 3.256;
#declare Cinnabar_IOR_w_1 = 2.905;
#declare Cinnabar_Birefringence_1 = 0.3510;

#declare Claraite_IOR_e_1 = 1.645;
#declare Claraite_IOR_w_1 = 1.751;
#declare Claraite_Birefringence_1 = 0.1060;

#declare Claringbullite_IOR_e_1 = 1.78;
#declare Claringbullite_IOR_w_1 = 1.782;
#declare Claringbullite_Birefringence_1 = 0.0020;

#declare Coalingite_IOR_e_1 = 1.56;
#declare Coalingite_IOR_e_2 = 1.59;
#declare Coalingite_IOR_w_1 = 1.588;
#declare Coalingite_IOR_w_2 = 1.635;
#declare Coalingite_Birefringence_1 = 0.0280;
#declare Coalingite_Birefringence_2 = 0.0450;

#declare Coffinite_IOR_a_1 = 1.73;
#declare Coffinite_IOR_a_2 = 1.75;
#declare Coffinite_IOR_b_1 = 1.73;
#declare Coffinite_IOR_b_2 = 1.75;
#declare Coffinite_Birefringence_1 = 0.0000;

#declare Colerainite_IOR_w_1 = 1.56;

#declare Colquiriite_IOR_e_1 = 1.385;
#declare Colquiriite_IOR_w_1 = 1.388;
#declare Colquiriite_Birefringence_1 = 0.0030;

#declare Combeite_IOR_e_1 = 1.598;
#declare Combeite_IOR_w_1 = 1.598;
#declare Combeite_Birefringence_1 = 0.0000;

#declare Comblainite_IOR_e_1 = 1.684;
#declare Comblainite_IOR_w_1 = 1.69;
#declare Comblainite_Birefringence_1 = 0.0060;

#declare Congolite_IOR_e_1 = 1.731;
#declare Congolite_IOR_w_1 = 1.755;
#declare Congolite_Birefringence_1 = 0.0240;

#declare Connellite_IOR_e_1 = 1.746;
#declare Connellite_IOR_e_2 = 1.758;
#declare Connellite_IOR_w_1 = 1.724;
#declare Connellite_IOR_w_2 = 1.738;
#declare Connellite_Birefringence_1 = 0.0200;
#declare Connellite_Birefringence_2 = 0.0220;

#declare Coombsite_IOR_e_1 = 1.6;
#declare Coombsite_IOR_w_1 = 1.619;
#declare Coombsite_Birefringence_1 = 0.0190;

#declare Coquimbite_IOR_e_1 = 1.557;
#declare Coquimbite_IOR_w_1 = 1.55;
#declare Coquimbite_Birefringence_1 = 0.0070;

#declare Cordylite_Ce_IOR_e_1 = 1.5984;
#declare Cordylite_Ce_IOR_w_1 = 1.775;
#declare Cordylite_Ce_Birefringence_1 = 0.1766;

#declare Corkite_IOR_e_1 = 1.93;
#declare Corkite_IOR_w_1 = 1.93;
#declare Corkite_Birefringence_1 = 0.0000;

#declare Corundum_IOR_e_1 = 1.76;
#declare Corundum_IOR_w_1 = 1.768;
#declare Corundum_Birefringence_1 = 0.0080;

#declare Cualstibite_IOR_e_1 = 1.644;
#declare Cualstibite_IOR_w_1 = 1.672;
#declare Cualstibite_Birefringence_1 = 0.0280;

#declare Cumengeite_IOR_e_1 = 1.926;
#declare Cumengeite_IOR_w_1 = 2.041;
#declare Cumengeite_Birefringence_1 = 0.1150;

#declare Cuprorivaite_IOR_e_1 = 1.59;
#declare Cuprorivaite_IOR_w_1 = 1.633;
#declare Cuprorivaite_Birefringence_1 = 0.0430;

#declare Cuprotungstite_IOR_e_1 = 2.1;
#declare Cuprotungstite_IOR_w_1 = 2.18;
#declare Cuprotungstite_Birefringence_1 = 0.0800;

#declare Cuzticite_IOR_e_1 = 2.05;
#declare Cuzticite_IOR_w_1 = 2.06;
#declare Cuzticite_Birefringence_1 = 0.0100;

#declare Cymrite_IOR_e_1 = 1.603;
#declare Cymrite_IOR_e_2 = 1.606;
#declare Cymrite_IOR_w_1 = 1.611;
#declare Cymrite_IOR_w_2 = 1.617;
#declare Cymrite_Birefringence_1 = 0.0080;
#declare Cymrite_Birefringence_2 = 0.0110;

#declare Cyrilovite_IOR_e_1 = 1.769;
#declare Cyrilovite_IOR_w_1 = 1.803;
#declare Cyrilovite_Birefringence_1 = 0.0340;

#declare Daqingshanite_Ce_IOR_e_1 = 1.609;
#declare Daqingshanite_Ce_IOR_w_1 = 1.708;
#declare Daqingshanite_Ce_Birefringence_1 = 0.0990;

#declare Darapiosite_IOR_e_1 = 1.575;
#declare Darapiosite_IOR_w_1 = 1.58;
#declare Darapiosite_Birefringence_1 = 0.0050;

#declare Daubreeite_IOR_e_1 = 1.91;
#declare Daubreeite_IOR_w_1 = 2.15;
#declare Daubreeite_Birefringence_1 = 0.2400;

#declare Davyne_IOR_e_1 = 1.517;
#declare Davyne_IOR_e_2 = 1.527;
#declare Davyne_IOR_w_1 = 1.518;
#declare Davyne_IOR_w_2 = 1.522;
#declare Davyne_Birefringence_1 = 0.0010;
#declare Davyne_Birefringence_2 = 0.0050;

#declare Dehrnite_IOR_e_1 = 1.59;
#declare Dehrnite_IOR_e_2 = 1.63;
#declare Dehrnite_IOR_w_1 = 1.6;
#declare Dehrnite_IOR_w_2 = 1.64;
#declare Dehrnite_Birefringence_1 = 0.0100;

#declare Deloneite_Ce_IOR_e_1 = 1.66;
#declare Deloneite_Ce_IOR_w_1 = 1.682;
#declare Deloneite_Ce_Birefringence_1 = 0.0220;

#declare Deltaite_IOR_e_1 = 1.64;
#declare Deltaite_IOR_w_1 = 1.63;
#declare Deltaite_Birefringence_1 = 0.0100;

#declare Denningite_IOR_e_1 = 2;
#declare Denningite_IOR_w_1 = 1.89;
#declare Denningite_Birefringence_1 = 0.1100;

#declare Dennisonite_IOR_e_1 = 1.59;
#declare Dennisonite_IOR_e_2 = 1.6;
#declare Dennisonite_IOR_w_1 = 1.59;
#declare Dennisonite_IOR_w_2 = 1.6;
#declare Dennisonite_Birefringence_1 = 0.0000;

#declare Desautelsite_IOR_e_1 = 1.547;
#declare Desautelsite_IOR_w_1 = 1.569;
#declare Desautelsite_Birefringence_1 = 0.0220;

#declare Despujolsite_IOR_e_1 = 1.682;
#declare Despujolsite_IOR_w_1 = 1.656;
#declare Despujolsite_Birefringence_1 = 0.0260;

#declare Diaboleite_IOR_e_1 = 1.85;
#declare Diaboleite_IOR_w_1 = 1.98;
#declare Diaboleite_Birefringence_1 = 0.1300;

#declare Diaoyudaoite_IOR_e_1 = 1.663;
#declare Diaoyudaoite_IOR_w_1 = 1.6876;
#declare Diaoyudaoite_Birefringence_1 = 0.0246;

#declare Dilithium_IOR_e_1 = 1.971;
#declare Dilithium_IOR_e_2 = 2.01;
#declare Dilithium_IOR_w_1 = 1.952;
#declare Dilithium_IOR_w_2 = 1.984;
#declare Dilithium_Birefringence_1 = 0.0190;
#declare Dilithium_Birefringence_2 = 0.0260;

#declare Diomignite_IOR_e_1 = 1.554;
#declare Diomignite_IOR_w_1 = 1.612;
#declare Diomignite_Birefringence_1 = 0.0580;

#declare Dioptase_IOR_e_1 = 1.697;
#declare Dioptase_IOR_e_2 = 1.709;
#declare Dioptase_IOR_w_1 = 1.644;
#declare Dioptase_IOR_w_2 = 1.658;
#declare Dioptase_Birefringence_1 = 0.0510;
#declare Dioptase_Birefringence_2 = 0.0530;

#declare Dixenite_IOR_e_1 = 1.73;
#declare Dixenite_IOR_w_1 = 1.97;
#declare Dixenite_Birefringence_1 = 0.2400;

#declare Dmisteinbergite_IOR_e_1 = 1.58;
#declare Dmisteinbergite_IOR_w_1 = 1.575;
#declare Dmisteinbergite_Birefringence_1 = 0.0050;

#declare Dolomite_IOR_e_1 = 1.5;
#declare Dolomite_IOR_w_1 = 1.679;
#declare Dolomite_IOR_w_2 = 1.681;
#declare Dolomite_Birefringence_1 = 0.1790;
#declare Dolomite_Birefringence_2 = 0.1810;

#declare Dorallcharite_IOR_e_1 = 1.768;
#declare Dorallcharite_IOR_w_1 = 1.822;
#declare Dorallcharite_Birefringence_1 = 0.0540;

#declare Dravite_IOR_e_1 = 1.612;
#declare Dravite_IOR_e_2 = 1.63;
#declare Dravite_IOR_w_1 = 1.631;
#declare Dravite_IOR_w_2 = 1.655;
#declare Dravite_Birefringence_1 = 0.0190;
#declare Dravite_Birefringence_2 = 0.0250;

#declare Dugganite_IOR_e_1 = 1.967;
#declare Dugganite_IOR_w_1 = 1.977;
#declare Dugganite_Birefringence_1 = 0.0100;

#declare Dusmatovite_IOR_e_1 = 1.586;
#declare Dusmatovite_IOR_w_1 = 1.59;
#declare Dusmatovite_Birefringence_1 = 0.0040;

#declare Dussertite_IOR_e_1 = 1.85;
#declare Dussertite_IOR_w_1 = 1.87;
#declare Dussertite_Birefringence_1 = 0.0200;

#declare Ecdemite_IOR_e_1 = 2.25;
#declare Ecdemite_IOR_w_1 = 2.32;
#declare Ecdemite_Birefringence_1 = 0.0700;

#declare Effenbergerite_IOR_e_1 = 1.593;
#declare Effenbergerite_IOR_w_1 = 1.633;
#declare Effenbergerite_Birefringence_1 = 0.0400;

#declare Eifelite_IOR_e_1 = 1.5443;
#declare Eifelite_IOR_e_2 = 1.5458;
#declare Eifelite_IOR_w_1 = 1.543;
#declare Eifelite_IOR_w_2 = 1.5445;
#declare Eifelite_Birefringence_1 = 0.0013;

#declare Eitelite_IOR_e_1 = 1.4502;
#declare Eitelite_IOR_w_1 = 1.6052;
#declare Eitelite_Birefringence_1 = 0.1550;

#declare Ekanite_IOR_e_1 = 1.568;
#declare Ekanite_IOR_w_1 = 1.58;
#declare Ekanite_Birefringence_1 = 0.0120;

#declare Ekaterinite_IOR_e_1 = 1.574;
#declare Ekaterinite_IOR_w_1 = 1.577;
#declare Ekaterinite_Birefringence_1 = 0.0030;

#declare Elbaite_IOR_e_1 = 1.615;
#declare Elbaite_IOR_e_2 = 1.632;
#declare Elbaite_IOR_w_1 = 1.635;
#declare Elbaite_IOR_w_2 = 1.65;
#declare Elbaite_Birefringence_1 = 0.0180;
#declare Elbaite_Birefringence_2 = 0.0200;

#declare Ellenbergerite_IOR_e_1 = 1.6538;
#declare Ellenbergerite_IOR_e_2 = 1.6697;
#declare Ellenbergerite_IOR_w_1 = 1.6553;
#declare Ellenbergerite_IOR_w_2 = 1.6789;
#declare Ellenbergerite_Birefringence_1 = 0.0015;
#declare Ellenbergerite_Birefringence_2 = 0.0092;

#declare Erionite_Ca_IOR_e_1 = 1.474;
#declare Erionite_Ca_IOR_w_1 = 1.4711;
#declare Erionite_Ca_Birefringence_1 = 0.0191;

#declare Erionite_K_IOR_e_1 = 1.474;
#declare Erionite_K_IOR_w_1 = 1.4711;
#declare Erionite_K_Birefringence_1 = 0.0191;

#declare Erionite_Na_IOR_e_1 = 1.474;
#declare Erionite_Na_IOR_w_1 = 1.4711;
#declare Erionite_Na_Birefringence_1 = 0.0191;

#declare Ernienickelite_IOR_w_1 = 1.97;

#declare Ettringite_IOR_e_1 = 1.47;
#declare Ettringite_IOR_w_1 = 1.491;
#declare Ettringite_Birefringence_1 = 0.0210;

#declare Eucryptite_IOR_e_1 = 1.586;
#declare Eucryptite_IOR_w_1 = 1.527;
#declare Eucryptite_Birefringence_1 = 0.0590;

#declare Eudialyte_IOR_e_1 = 1.61;
#declare Eudialyte_IOR_e_2 = 1.613;
#declare Eudialyte_IOR_w_1 = 1.606;
#declare Eudialyte_IOR_w_2 = 1.61;
#declare Eudialyte_Birefringence_1 = 0.0030;
#declare Eudialyte_Birefringence_2 = 0.0040;

#declare Ewaldite_IOR_e_1 = 1.572;
#declare Ewaldite_IOR_w_1 = 1.646;
#declare Ewaldite_Birefringence_1 = 0.0740;

#declare Eylettersite_IOR_a_1 = 1.635;
#declare Eylettersite_IOR_b_1 = 1.635;
#declare Eylettersite_Birefringence_1 = 0.0000;

#declare Faheyite_IOR_e_1 = 1.652;
#declare Faheyite_IOR_w_1 = 1.631;
#declare Faheyite_Birefringence_1 = 0.0210;

#declare Fairchildite_IOR_e_1 = 1.478;
#declare Fairchildite_IOR_w_1 = 1.532;
#declare Fairchildite_Birefringence_1 = 0.0540;

#declare Felsobanyaite_IOR_e_1 = 1.518;
#declare Felsobanyaite_IOR_w_1 = 1.516;
#declare Felsobanyaite_Birefringence_1 = 0.0020;

#declare Fergusonite_Ce_IOR_e_1 = 2.2;
#declare Fergusonite_Ce_IOR_w_1 = 2.3;
#declare Fergusonite_Ce_Birefringence_1 = 0.1000;

#declare Fergusonite_Nd_IOR_e_1 = 2.2;
#declare Fergusonite_Nd_IOR_w_1 = 2.3;
#declare Fergusonite_Nd_Birefringence_1 = 0.1000;

#declare Fermorite_IOR_e_1 = 1.655;
#declare Fermorite_IOR_w_1 = 1.66;
#declare Fermorite_Birefringence_1 = 0.0050;

#declare Ferrinatrite_IOR_e_1 = 1.627;
#declare Ferrinatrite_IOR_w_1 = 1.559;
#declare Ferrinatrite_Birefringence_1 = 0.0680;

#declare Ferritungstite_IOR_a_1 = 2.09;
#declare Ferritungstite_IOR_a_2 = 2.15;
#declare Ferritungstite_IOR_b_1 = 2.09;
#declare Ferritungstite_IOR_b_2 = 2.15;
#declare Ferritungstite_Birefringence_1 = 0.0000;

#declare Ferropyrosmalite_IOR_e_1 = 1.64;
#declare Ferropyrosmalite_IOR_w_1 = 1.68;
#declare Ferropyrosmalite_Birefringence_1 = 0.0400;

#declare Feruvite_IOR_e_1 = 1.669;
#declare Feruvite_IOR_w_1 = 1.687;
#declare Feruvite_Birefringence_1 = 0.0180;

#declare Fibroferrite_IOR_e_1 = 1.57;
#declare Fibroferrite_IOR_w_1 = 1.532;
#declare Fibroferrite_Birefringence_1 = 0.0380;

#declare Fillowite_IOR_e_1 = 1.676;
#declare Fillowite_IOR_w_1 = 1.671;
#declare Fillowite_Birefringence_1 = 0.0010;

#declare Finnemanite_IOR_e_1 = 2.2847;
#declare Finnemanite_IOR_w_1 = 2.2949;
#declare Finnemanite_Birefringence_1 = 0.0102;

#declare Fleischerite_IOR_e_1 = 1.776;
#declare Fleischerite_IOR_w_1 = 1.747;
#declare Fleischerite_Birefringence_1 = 0.0290;

#declare Florencite_Ce_IOR_e_1 = 1.776;
#declare Florencite_Ce_IOR_w_1 = 1.747;
#declare Florencite_Ce_Birefringence_1 = 0.0290;

#declare Florencite_La_IOR_e_1 = 1.701;
#declare Florencite_La_IOR_w_1 = 1.694;
#declare Florencite_La_Birefringence_1 = 0.0070;

#declare Florencite_Nd_IOR_e_1 = 1.73;
#declare Florencite_Nd_IOR_w_1 = 1.72;
#declare Florencite_Nd_Birefringence_1 = 0.0100;

#declare Fluoborite_IOR_e_1 = 1.534;
#declare Fluoborite_IOR_w_1 = 1.57;
#declare Fluoborite_Birefringence_1 = 0.0360;

#declare Fluocerite_Ce_IOR_e_1 = 1.607;
#declare Fluocerite_Ce_IOR_e_2 = 1.611;
#declare Fluocerite_Ce_IOR_w_1 = 1.612;
#declare Fluocerite_Ce_IOR_w_2 = 1.618;
#declare Fluocerite_Ce_Birefringence_1 = 0.0050;
#declare Fluocerite_Ce_Birefringence_2 = 0.0070;

#declare Fluocerite_La_IOR_e_1 = 1.603;
#declare Fluocerite_La_IOR_w_1 = 1.609;
#declare Fluocerite_La_Birefringence_1 = 0.0060;

#declare Fluorapatite_IOR_e_1 = 1.6328;
#declare Fluorapatite_IOR_w_1 = 1.6357;
#declare Fluorapatite_Birefringence_1 = 0.0029;

#declare Fluorapophyllite_IOR_e_1 = 1.536;
#declare Fluorapophyllite_IOR_w_1 = 1.5345;
#declare Fluorapophyllite_Birefringence_1 = 0.0015;

#declare Fluorbritholite_Ce_IOR_e_1 = 1.786;
#declare Fluorbritholite_Ce_IOR_w_1 = 1.792;
#declare Fluorbritholite_Ce_Birefringence_1 = 0.0060;

#declare Fluorcaphite_IOR_e_1 = 1.637;
#declare Fluorcaphite_IOR_w_1 = 1.649;
#declare Fluorcaphite_Birefringence_1 = 0.0120;

#declare Fluorellestadite_IOR_e_1 = 1.632;
#declare Fluorellestadite_IOR_w_1 = 1.638;
#declare Fluorellestadite_Birefringence_1 = 0.0060;

#declare Foitite_IOR_e_1 = 1.642;
#declare Foitite_IOR_w_1 = 1.664;
#declare Foitite_Birefringence_1 = 0.0220;

#declare Franciscanite_III_IOR_e_1 = 1.876;
#declare Franciscanite_III_IOR_w_1 = 1.859;
#declare Franciscanite_III_Birefringence_1 = 0.0170;

#declare Franciscanite_VIII_IOR_e_1 = 1.876;
#declare Franciscanite_VIII_IOR_w_1 = 1.859;
#declare Franciscanite_VIII_Birefringence_1 = 0.0170;

#declare Francoanellite_IOR_e_1 = 1.515;
#declare Francoanellite_IOR_w_1 = 1.51;
#declare Francoanellite_Birefringence_1 = 0.0050;

#declare Franzinite_IOR_e_1 = 1.512;
#declare Franzinite_IOR_w_1 = 1.51;
#declare Franzinite_Birefringence_1 = 0.0020;

#declare Fresnoite_IOR_e_1 = 1.765;
#declare Fresnoite_IOR_w_1 = 1.775;
#declare Fresnoite_Birefringence_1 = 0.0100;

#declare Fuenzalidaite_IOR_e_1 = 1.615;
#declare Fuenzalidaite_IOR_w_1 = 1.622;
#declare Fuenzalidaite_Birefringence_1 = 0.0070;

#declare Gagarinite_Y_IOR_e_1 = 1.492;
#declare Gagarinite_Y_IOR_w_1 = 1.472;
#declare Gagarinite_Y_Birefringence_1 = 0.0200;

#declare Gainesite_IOR_e_1 = 1.63;
#declare Gainesite_IOR_w_1 = 1.618;
#declare Gainesite_Birefringence_1 = 0.0120;

#declare Galeite_IOR_e_1 = 1.449;
#declare Galeite_IOR_w_1 = 1.447;
#declare Galeite_Birefringence_1 = 0.0020;

#declare Galileiite_IOR_e_1 = 1.75;
#declare Galileiite_IOR_w_1 = 1.72;
#declare Galileiite_Birefringence_1 = 0.0300;

#declare Gallobeudantite_IOR_e_1 = 1.75;
#declare Gallobeudantite_IOR_w_1 = 1.763;
#declare Gallobeudantite_Birefringence_1 = 0.0130;

#declare Ganomalite_IOR_e_1 = 1.945;
#declare Ganomalite_IOR_w_1 = 1.91;
#declare Ganomalite_Birefringence_1 = 0.0350;

#declare Gaspeite_IOR_e_1 = 1.61;
#declare Gaspeite_IOR_w_1 = 1.83;
#declare Gaspeite_Birefringence_1 = 0.2200;

#declare Gaudefroyite_IOR_e_1 = 2.015;
#declare Gaudefroyite_IOR_e_2 = 2.02;
#declare Gaudefroyite_IOR_w_1 = 1.805;
#declare Gaudefroyite_IOR_w_2 = 1.81;
#declare Gaudefroyite_Birefringence_1 = 0.2100;

#declare Gehlenite_IOR_e_1 = 1.66;
#declare Gehlenite_IOR_w_1 = 1.67;
#declare Gehlenite_Birefringence_1 = 0.0100;

#declare Geikielite_IOR_e_1 = 1.95;
#declare Geikielite_IOR_w_1 = 2.31;
#declare Geikielite_Birefringence_1 = 0.3600;

#declare Gillespite_IOR_e_1 = 1.619;
#declare Gillespite_IOR_w_1 = 1.621;
#declare Gillespite_Birefringence_1 = 0.0020;

#declare Giuseppettite_IOR_e_1 = 1.507;
#declare Giuseppettite_IOR_w_1 = 1.491;
#declare Giuseppettite_Birefringence_1 = 0.0160;

#declare Glucine_IOR_e_1 = 1.571;
#declare Glucine_IOR_w_1 = 1.547;
#declare Glucine_Birefringence_1 = 0.0240;

#declare Gmelinite_IOR_a_1 = 1.474;
#declare Gmelinite_IOR_a_2 = 1.481;
#declare Gmelinite_IOR_b_1 = 1.476;
#declare Gmelinite_IOR_b_2 = 1.494;
#declare Gmelinite_Birefringence_1 = 0.0020;
#declare Gmelinite_Birefringence_2 = 0.0130;

#declare Gmelinite_Ca_IOR_a_1 = 1.474;
#declare Gmelinite_Ca_IOR_a_2 = 1.481;
#declare Gmelinite_Ca_IOR_b_1 = 1.476;
#declare Gmelinite_Ca_IOR_b_2 = 1.494;
#declare Gmelinite_Ca_Birefringence_1 = 0.0020;
#declare Gmelinite_Ca_Birefringence_2 = 0.0130;

#declare Gmelinite_K_IOR_a_1 = 1.474;
#declare Gmelinite_K_IOR_a_2 = 1.481;
#declare Gmelinite_K_IOR_b_1 = 1.476;
#declare Gmelinite_K_IOR_b_2 = 1.494;
#declare Gmelinite_K_Birefringence_1 = 0.0020;
#declare Gmelinite_K_Birefringence_2 = 0.0130;

#declare Gmelinite_Na_IOR_a_1 = 1.474;
#declare Gmelinite_Na_IOR_a_2 = 1.481;
#declare Gmelinite_Na_IOR_b_1 = 1.476;
#declare Gmelinite_Na_IOR_b_2 = 1.494;
#declare Gmelinite_Na_Birefringence_1 = 0.0020;
#declare Gmelinite_Na_Birefringence_2 = 0.0130;

#declare Godovikovite_IOR_e_1 = 1.581;
#declare Godovikovite_IOR_w_1 = 1.572;
#declare Godovikovite_Birefringence_1 = 0.0090;

#declare Gordaite_IOR_e_1 = 1.5382;
#declare Gordaite_IOR_w_1 = 1.5607;
#declare Gordaite_Birefringence_1 = 0.0225;

#declare Goudeyite_IOR_e_1 = 1.765;
#declare Goudeyite_IOR_w_1 = 1.704;
#declare Goudeyite_Birefringence_1 = 0.0610;

#declare Goyazite_IOR_e_1 = 1.63;
#declare Goyazite_IOR_w_1 = 1.62;
#declare Goyazite_Birefringence_1 = 0.0100;

#declare Greenockite_IOR_e_1 = 2.506;
#declare Greenockite_IOR_w_1 = 2.529;
#declare Greenockite_Birefringence_1 = 0.0230;

#declare Grimselite_IOR_e_1 = 1.48;
#declare Grimselite_IOR_w_1 = 1.601;
#declare Grimselite_Birefringence_1 = 0.1210;

#declare Guarinoite_IOR_e_1 = 1.544;
#declare Guarinoite_IOR_w_1 = 1.548;
#declare Guarinoite_Birefringence_1 = 0.0040;

#declare Gugiaite_IOR_e_1 = 1.672;
#declare Gugiaite_IOR_w_1 = 1.664;
#declare Gugiaite_Birefringence_1 = 0.0080;

#declare Hafnon_IOR_e_1 = 1.98;
#declare Hafnon_IOR_e_2 = 2.03;
#declare Hafnon_IOR_w_1 = 1.93;
#declare Hafnon_IOR_w_2 = 1.97;
#declare Hafnon_Birefringence_1 = 0.0500;
#declare Hafnon_Birefringence_2 = 0.0600;

#declare Hanksite_IOR_e_1 = 1.461;
#declare Hanksite_IOR_w_1 = 1.481;
#declare Hanksite_Birefringence_1 = 0.0200;

#declare Hardystonite_IOR_e_1 = 1.661;
#declare Hardystonite_IOR_w_1 = 1.672;
#declare Hardystonite_Birefringence_1 = 0.0110;

#declare Harkerite_IOR_a_1 = 1.649;
#declare Harkerite_IOR_a_2 = 1.653;
#declare Harkerite_IOR_b_1 = 1.649;
#declare Harkerite_IOR_b_2 = 1.653;
#declare Harkerite_Birefringence_1 = 0.0000;

#declare Harrisonite_IOR_e_1 = 1.759;
#declare Harrisonite_IOR_w_1 = 1.77;
#declare Harrisonite_Birefringence_1 = 0.0110;

#declare Hauckite_IOR_e_1 = 1.638;
#declare Hauckite_IOR_w_1 = 1.63;
#declare Hauckite_Birefringence_1 = 0.0080;

#declare Hedyphane_IOR_e_1 = 1.958;
#declare Hedyphane_IOR_w_1 = 1.948;
#declare Hedyphane_Birefringence_1 = 0.0100;

#declare Heinrichite_IOR_e_1 = 1.573;
#declare Heinrichite_IOR_w_1 = 1.605;
#declare Heinrichite_Birefringence_1 = 0.0320;

#declare Hematolite_IOR_e_1 = 1.714;
#declare Hematolite_IOR_w_1 = 1.733;
#declare Hematolite_Birefringence_1 = 0.0190;

#declare Henritermierite_IOR_e_1 = 1.8;
#declare Henritermierite_IOR_w_1 = 1.765;
#declare Henritermierite_Birefringence_1 = 0.0350;

#declare Hetaerolite_IOR_e_1 = 2.14;
#declare Hetaerolite_IOR_w_1 = 2.34;
#declare Hetaerolite_Birefringence_1 = 0.2000;

#declare Hiarneite_IOR_e_1 = 2.16;
#declare Hiarneite_IOR_w_1 = 2.12;
#declare Hiarneite_Birefringence_1 = 0.0400;

#declare Hidalgoite_IOR_b_1 = 1.713;

#declare Hilairite_IOR_e_1 = 1.596;
#declare Hilairite_IOR_w_1 = 1.609;
#declare Hilairite_Birefringence_1 = 0.0130;

#declare Hinsdalite_IOR_e_1 = 1.7;
#declare Hinsdalite_IOR_w_1 = 1.67;
#declare Hinsdalite_Birefringence_1 = 0.0300;

#declare Hogbomite_15R_18R_24R_IOR_e_1 = 1.803;
#declare Hogbomite_15R_18R_24R_IOR_w_1 = 1.853;
#declare Hogbomite_15R_18R_24R_Birefringence_1 = 0.0500;

#declare Hogbomite_4H_5H_6H_15H_IOR_e_1 = 1.803;
#declare Hogbomite_4H_5H_6H_15H_IOR_w_1 = 1.853;
#declare Hogbomite_4H_5H_6H_15H_Birefringence_1 = 0.0500;

#declare Hogbomite_8H_IOR_e_1 = 1.803;
#declare Hogbomite_8H_IOR_w_1 = 1.853;
#declare Hogbomite_8H_Birefringence_1 = 0.0500;

#declare Holtedahlite_IOR_e_1 = 1.597;
#declare Holtedahlite_IOR_w_1 = 1.599;
#declare Holtedahlite_Birefringence_1 = 0.0020;

#declare Huanghoite_Ce_IOR_e_1 = 1.603;
#declare Huanghoite_Ce_IOR_w_1 = 1.765;
#declare Huanghoite_Ce_Birefringence_1 = 0.1620;

#declare Humberstonite_IOR_e_1 = 1.436;
#declare Humberstonite_IOR_w_1 = 1.474;
#declare Humberstonite_Birefringence_1 = 0.0380;

#declare Hydrocerussite_IOR_e_1 = 1.94;
#declare Hydrocerussite_IOR_w_1 = 2.09;
#declare Hydrocerussite_Birefringence_1 = 0.1500;

#declare Hydrohetaerolite_IOR_e_1 = 2.1;
#declare Hydrohetaerolite_IOR_w_1 = 2.26;
#declare Hydrohetaerolite_Birefringence_1 = 0.1600;

#declare Hydrohonessite_IOR_e_1 = 1.59;
#declare Hydrohonessite_IOR_w_1 = 1.63;
#declare Hydrohonessite_Birefringence_1 = 0.0400;

#declare Hydroniumjarosite_IOR_e_1 = 1.82;
#declare Hydroniumjarosite_IOR_w_1 = 1.82;
#declare Hydroniumjarosite_Birefringence_1 = 0.0000;

#declare Hydrotalcite_IOR_e_1 = 1.495;
#declare Hydrotalcite_IOR_e_2 = 1.529;
#declare Hydrotalcite_IOR_w_1 = 1.511;
#declare Hydrotalcite_IOR_w_2 = 1.531;
#declare Hydrotalcite_Birefringence_1 = 0.0020;
#declare Hydrotalcite_Birefringence_2 = 0.0160;

#declare Hydroxyapophyllite_IOR_e_1 = 1.543;
#declare Hydroxyapophyllite_IOR_w_1 = 1.542;
#declare Hydroxyapophyllite_Birefringence_1 = 0.0010;

#declare Hydroxycancrinite_IOR_e_1 = 1.494;
#declare Hydroxycancrinite_IOR_w_1 = 1.501;
#declare Hydroxycancrinite_Birefringence_1 = 0.0070;

#declare Hydroxylapatite_IOR_e_1 = 1.644;
#declare Hydroxylapatite_IOR_w_1 = 1.651;
#declare Hydroxylapatite_Birefringence_1 = 0.0070;

#declare Hydroxylbastnasite_Ce_IOR_e_1 = 1.87;
#declare Hydroxylbastnasite_Ce_IOR_w_1 = 1.76;
#declare Hydroxylbastnasite_Ce_Birefringence_1 = 0.1100;

#declare Hydroxylbastnasite_Nd_IOR_e_1 = 1.81;
#declare Hydroxylbastnasite_Nd_IOR_w_1 = 1.715;
#declare Hydroxylbastnasite_Nd_Birefringence_1 = 0.0950;

#declare Hydroxylellestadite_IOR_e_1 = 1.65;
#declare Hydroxylellestadite_IOR_w_1 = 1.654;
#declare Hydroxylellestadite_Birefringence_1 = 0.0040;

#declare Hypercinnabar_IOR_e_1 = 2.85;
#declare Hypercinnabar_IOR_w_1 = 2.61;
#declare Hypercinnabar_Birefringence_1 = 0.2400;

#declare Hyttsjoite_IOR_e_1 = 1.815;
#declare Hyttsjoite_IOR_w_1 = 1.845;
#declare Hyttsjoite_Birefringence_1 = 0.0300;

#declare Ice_IOR_a_1 = 1.32;
#declare Ice_IOR_b_1 = 1.33;
#declare Ice_Birefringence_1 = 0.0100;

#declare Ilimaussite_Ce_IOR_e_1 = 1.695;
#declare Ilimaussite_Ce_IOR_w_1 = 1.689;
#declare Ilimaussite_Ce_Birefringence_1 = 0.0060;

#declare Iltisite_IOR_e_1 = 2.1;
#declare Iltisite_IOR_w_1 = 2.3;
#declare Iltisite_Birefringence_1 = 0.2000;

#declare IMA95_025_IOR_b_1 = 1.532;

#declare IMA96_008_IOR_e_1 = 1.619;
#declare IMA96_008_IOR_w_1 = 1.625;
#declare IMA96_008_Birefringence_1 = 0.0060;

#declare IMA96_019_IOR_e_1 = 1.563;
#declare IMA96_019_IOR_w_1 = 1.538;
#declare IMA96_019_Birefringence_1 = 0.0250;

#declare IMA96_038_IOR_e_1 = 1.565;
#declare IMA96_038_IOR_w_1 = 1.549;
#declare IMA96_038_Birefringence_1 = 0.0160;

#declare IMA96_040_IOR_e_1 = 2.16;
#declare IMA96_040_IOR_w_1 = 2.12;
#declare IMA96_040_Birefringence_1 = 0.0400;

#declare IMA96_043_IOR_e_1 = 1.801;
#declare IMA96_043_IOR_w_1 = 1.76;
#declare IMA96_043_Birefringence_1 = 0.0410;

#declare IMA96_061_IOR_a_1 = 1.72;
#declare IMA96_061_IOR_b_1 = 1.72;
#declare IMA96_061_Birefringence_1 = 0.0000;

#declare IMA97_009_IOR_e_1 = 1.765;
#declare IMA97_009_IOR_w_1 = 1.688;
#declare IMA97_009_Birefringence_1 = 0.0770;

#declare IMA97_018_IOR_e_1 = 1.562;
#declare IMA97_018_IOR_w_1 = 1.561;
#declare IMA97_018_Birefringence_1 = 0.0010;

#declare IMA97_026_IOR_e_1 = 1.725;
#declare IMA97_026_IOR_w_1 = 1.721;
#declare IMA97_026_Birefringence_1 = 0.0040;

#declare IMA97_047_IOR_e_1 = 1.4;
#declare IMA97_047_IOR_w_1 = 1.54;
#declare IMA97_047_Birefringence_1 = 0.1400;

#declare Indialite_IOR_e_1 = 1.534;
#declare Indialite_IOR_w_1 = 1.539;
#declare Indialite_Birefringence_1 = 0.0050;

#declare Ingersonite_IOR_e_1 = 1.91;
#declare Ingersonite_IOR_w_1 = 1.93;
#declare Ingersonite_Birefringence_1 = 0.0200;

#declare Iodargyrite_IOR_e_1 = 2.22;
#declare Iodargyrite_IOR_w_1 = 2.21;
#declare Iodargyrite_Birefringence_1 = 0.0100;

#declare Iowaite_IOR_e_1 = 1.533;
#declare Iowaite_IOR_e_2 = 1.543;
#declare Iowaite_IOR_w_1 = 1.543;
#declare Iowaite_IOR_w_2 = 1.561;
#declare Iowaite_Birefringence_1 = 0.0100;
#declare Iowaite_Birefringence_2 = 0.0180;

#declare Iquiqueite_IOR_e_1 = 1.447;
#declare Iquiqueite_IOR_w_1 = 1.502;
#declare Iquiqueite_Birefringence_1 = 0.0550;

#declare Iraqite_La_IOR_e_1 = 1.585;
#declare Iraqite_La_IOR_w_1 = 1.59;
#declare Iraqite_La_Birefringence_1 = 0.0050;

#declare Jaffeite_IOR_e_1 = 1.604;
#declare Jaffeite_IOR_w_1 = 1.596;
#declare Jaffeite_Birefringence_1 = 0.0080;

#declare Jagoite_IOR_w_1 = 2;

#declare Jamborite_IOR_e_1 = 1.602;
#declare Jamborite_IOR_w_1 = 1.607;
#declare Jamborite_Birefringence_1 = 0.0050;

#declare Jarosite_IOR_e_1 = 1.713;
#declare Jarosite_IOR_e_2 = 1.715;
#declare Jarosite_IOR_w_1 = 1.815;
#declare Jarosite_IOR_w_2 = 1.82;
#declare Jarosite_Birefringence_1 = 0.1020;
#declare Jarosite_Birefringence_2 = 0.1050;

#declare Jasmundite_IOR_e_1 = 1.728;
#declare Jasmundite_IOR_w_1 = 1.715;
#declare Jasmundite_Birefringence_1 = 0.0130;

#declare Jeanbandyite_IOR_e_1 = 1.833;
#declare Jeanbandyite_IOR_w_1 = 1.837;
#declare Jeanbandyite_Birefringence_1 = 0.0040;

#declare Jeremejevite_IOR_e_1 = 1.64;
#declare Jeremejevite_IOR_w_1 = 1.653;
#declare Jeremejevite_Birefringence_1 = 0.0130;

#declare Johnbaumite_IOR_e_1 = 1.684;
#declare Johnbaumite_IOR_w_1 = 1.687;
#declare Johnbaumite_Birefringence_1 = 0.0030;

#declare Johnsomervilleite_IOR_a_1 = 1.655;
#declare Johnsomervilleite_IOR_b_1 = 1.655;
#declare Johnsomervilleite_Birefringence_1 = 0.0000;

#declare Jouravskite_IOR_e_1 = 1.54;
#declare Jouravskite_IOR_w_1 = 1.556;
#declare Jouravskite_Birefringence_1 = 0.0160;

#declare Julienite_IOR_e_1 = 1.645;
#declare Julienite_IOR_w_1 = 1.556;
#declare Julienite_Birefringence_1 = 0.0890;

#declare Kafehydrocyanite_IOR_e_1 = 1.584;
#declare Kafehydrocyanite_IOR_w_1 = 1.577;
#declare Kafehydrocyanite_Birefringence_1 = 0.0070;

#declare Kahlerite_IOR_e_1 = 1.632;
#declare Kahlerite_IOR_w_1 = 1.634;
#declare Kahlerite_Birefringence_1 = 0.0020;

#declare Kalborsite_IOR_e_1 = 1.525;
#declare Kalborsite_IOR_w_1 = 1.525;
#declare Kalborsite_Birefringence_1 = 0.0000;

#declare Kaliophilite_IOR_e_1 = 1.527;
#declare Kaliophilite_IOR_w_1 = 1.532;
#declare Kaliophilite_Birefringence_1 = 0.0050;

#declare Kalistrontite_IOR_e_1 = 1.549;
#declare Kalistrontite_IOR_w_1 = 1.569;
#declare Kalistrontite_Birefringence_1 = 0.0200;

#declare Kalsilite_IOR_e_1 = 1.532;
#declare Kalsilite_IOR_e_2 = 1.537;
#declare Kalsilite_IOR_w_1 = 1.538;
#declare Kalsilite_IOR_w_2 = 1.543;
#declare Kalsilite_Birefringence_1 = 0.0060;

#declare Kamaishilite_IOR_b_1 = 1.629;

#declare Kambaldaite_IOR_e_1 = 1.69;
#declare Kambaldaite_IOR_w_1 = 1.65;
#declare Kambaldaite_Birefringence_1 = 0.0400;

#declare Kamphaugite_Y_IOR_e_1 = 1.627;
#declare Kamphaugite_Y_IOR_w_1 = 1.663;
#declare Kamphaugite_Y_Birefringence_1 = 0.0360;

#declare Karnasurtite_Ce_IOR_e_1 = 1.595;
#declare Karnasurtite_Ce_IOR_w_1 = 1.617;
#declare Karnasurtite_Ce_Birefringence_1 = 0.0220;

#declare Kazakovite_IOR_e_1 = 1.625;
#declare Kazakovite_IOR_w_1 = 1.648;
#declare Kazakovite_Birefringence_1 = 0.0230;

#declare Kellyite_IOR_e_1 = 1.639;
#declare Kellyite_IOR_w_1 = 1.646;
#declare Kellyite_Birefringence_1 = 0.0070;

#declare Kemmlitzite_IOR_e_1 = 1.707;
#declare Kemmlitzite_IOR_w_1 = 1.701;
#declare Kemmlitzite_Birefringence_1 = 0.0060;

#declare Kentbrooksite_IOR_e_1 = 1.623;
#declare Kentbrooksite_IOR_w_1 = 1.628;
#declare Kentbrooksite_Birefringence_1 = 0.0050;

#declare Khanneshite_IOR_e_1 = 1.609;
#declare Khanneshite_IOR_e_2 = 1.61;
#declare Khanneshite_IOR_w_1 = 1.62;
#declare Khanneshite_IOR_w_2 = 1.623;
#declare Khanneshite_Birefringence_1 = 0.0110;
#declare Khanneshite_Birefringence_2 = 0.0130;

#declare Kintoreite_IOR_e_1 = 1.935;
#declare Kintoreite_IOR_w_1 = 1.935;
#declare Kintoreite_IOR_w_2 = 1.955;
#declare Kintoreite_Birefringence_1 = 0.0000;
#declare Kintoreite_Birefringence_2 = 0.0200;

#declare Kittatinnyite_IOR_w_1 = 1.727;

#declare Kleberite_IOR_a_1 = 1.8;
#declare Kleberite_IOR_a_2 = 2;

#declare Kleinite_IOR_e_1 = 2.21;
#declare Kleinite_IOR_w_1 = 2.19;
#declare Kleinite_Birefringence_1 = 0.0200;

#declare Koenenite_IOR_e_1 = 1.55;
#declare Koenenite_IOR_w_1 = 1.53;
#declare Koenenite_Birefringence_1 = 0.0200;

#declare Komkovite_IOR_e_1 = 1.644;
#declare Komkovite_IOR_w_1 = 1.671;
#declare Komkovite_Birefringence_1 = 0.0270;

#declare Kosnarite_IOR_e_1 = 1.682;
#declare Kosnarite_IOR_w_1 = 1.656;
#declare Kosnarite_Birefringence_1 = 0.0260;

#declare Kraisslite_IOR_e_1 = 1.805;

#declare Kutnohorite_IOR_e_1 = 1.535;
#declare Kutnohorite_IOR_w_1 = 1.727;
#declare Kutnohorite_Birefringence_1 = 0.1920;

#declare Kuzelite_IOR_e_1 = 1.485;
#declare Kuzelite_IOR_w_1 = 1.504;
#declare Kuzelite_Birefringence_1 = 0.0190;

#declare Landauite_IOR_e_1 = 2.373;
#declare Landauite_IOR_w_1 = 2.388;
#declare Landauite_Birefringence_1 = 0.0150;

#declare Lannonite_IOR_e_1 = 1.478;
#declare Lannonite_IOR_w_1 = 1.46;
#declare Lannonite_Birefringence_1 = 0.0180;

#declare Laurelite_IOR_e_1 = 1.946;
#declare Laurelite_IOR_w_1 = 1.903;
#declare Laurelite_Birefringence_1 = 0.0430;

#declare Lawrencite_IOR_e_1 = 1.576;
#declare Lawrencite_IOR_w_1 = 1.576;
#declare Lawrencite_Birefringence_1 = 0.0000;

#declare Leifite_IOR_e_1 = 1.5224;
#declare Leifite_IOR_w_1 = 1.5117;
#declare Leifite_Birefringence_1 = 0.0107;

#declare Leisingite_IOR_e_1 = 1.581;
#declare Leisingite_IOR_w_1 = 1.803;
#declare Leisingite_Birefringence_1 = 0.2220;

#declare Levyne_IOR_e_1 = 1.487;
#declare Levyne_IOR_e_2 = 1.502;
#declare Levyne_IOR_w_1 = 1.489;
#declare Levyne_IOR_w_2 = 1.51;
#declare Levyne_Birefringence_1 = 0.0020;
#declare Levyne_Birefringence_2 = 0.0080;

#declare Levyne_Ca_IOR_e_1 = 1.487;
#declare Levyne_Ca_IOR_e_2 = 1.502;
#declare Levyne_Ca_IOR_w_1 = 1.489;
#declare Levyne_Ca_IOR_w_2 = 1.51;
#declare Levyne_Ca_Birefringence_1 = 0.0020;
#declare Levyne_Ca_Birefringence_2 = 0.0080;

#declare Levyne_Na_IOR_e_1 = 1.487;
#declare Levyne_Na_IOR_e_2 = 1.502;
#declare Levyne_Na_IOR_w_1 = 1.489;
#declare Levyne_Na_IOR_w_2 = 1.51;
#declare Levyne_Na_Birefringence_1 = 0.0020;
#declare Levyne_Na_Birefringence_2 = 0.0080;

#declare Lewistonite_IOR_e_1 = 1.61;
#declare Lewistonite_IOR_w_1 = 1.62;
#declare Lewistonite_Birefringence_1 = 0.0100;

#declare Liandratite_IOR_b_1 = 1.83;

#declare Liddicoatite_IOR_e_1 = 1.621;
#declare Liddicoatite_IOR_w_1 = 1.637;
#declare Liddicoatite_Birefringence_1 = 0.0160;

#declare Liottite_IOR_e_1 = 1.528;
#declare Liottite_IOR_w_1 = 1.53;
#declare Liottite_Birefringence_1 = 0.0020;

#declare Litharge_IOR_e_1 = 2.535;
#declare Litharge_IOR_w_1 = 2.665;
#declare Litharge_Birefringence_1 = 0.1300;

#declare Lonsdaleite_IOR_a_1 = 2.404;
#declare Lonsdaleite_IOR_b_1 = 2.404;
#declare Lonsdaleite_Birefringence_1 = 0.0000;

#declare Lorettoite_IOR_e_1 = 2.33;
#declare Lorettoite_IOR_w_1 = 2.4;
#declare Lorettoite_Birefringence_1 = 0.0700;

#declare Lourenswalsite_IOR_e_1 = 1.815;
#declare Lourenswalsite_IOR_w_1 = 1.84;
#declare Lourenswalsite_Birefringence_1 = 0.0250;

#declare Lovozerite_IOR_e_1 = 1.549;
#declare Lovozerite_IOR_w_1 = 1.561;
#declare Lovozerite_Birefringence_1 = 0.0120;

#declare Loweite_IOR_e_1 = 1.471;
#declare Loweite_IOR_w_1 = 1.49;
#declare Loweite_Birefringence_1 = 0.0190;

#declare Lukechangite_Ce_IOR_e_1 = 1.542;
#declare Lukechangite_Ce_IOR_w_1 = 1.728;
#declare Lukechangite_Ce_Birefringence_1 = 0.1860;

#declare Machatschkiite_IOR_e_1 = 1.585;
#declare Machatschkiite_IOR_w_1 = 1.593;
#declare Machatschkiite_Birefringence_1 = 0.0080;

#declare Mackayite_IOR_e_1 = 2.21;
#declare Mackayite_IOR_w_1 = 2.19;
#declare Mackayite_Birefringence_1 = 0.0200;

#declare Magadiite_IOR_e_1 = 1.47;
#declare Magadiite_IOR_w_1 = 1.48;
#declare Magadiite_Birefringence_1 = 0.0100;

#declare Magnesite_IOR_e_1 = 1.7;
#declare Magnesite_IOR_w_1 = 1.508;
#declare Magnesite_IOR_w_2 = 1.51;
#declare Magnesite_Birefringence_1 = 0.1900;
#declare Magnesite_Birefringence_2 = 0.1920;

#declare Mahnertite_IOR_e_1 = 1.635;
#declare Mahnertite_IOR_w_1 = 1.686;
#declare Mahnertite_Birefringence_1 = 0.0510;

#declare Malladrite_IOR_e_1 = 1.3089;
#declare Malladrite_IOR_w_1 = 1.3125;
#declare Malladrite_Birefringence_1 = 0.0036;

#declare Manasseite_IOR_e_1 = 1.51;
#declare Manasseite_IOR_w_1 = 1.524;
#declare Manasseite_Birefringence_1 = 0.0140;

#declare Manganarsite_IOR_e_1 = 1.78;
#declare Manganarsite_IOR_w_1 = 1.81;
#declare Manganarsite_Birefringence_1 = 0.0300;

#declare Manganpyrosmalite_IOR_e_1 = 1.64;
#declare Manganpyrosmalite_IOR_w_1 = 1.68;
#declare Manganpyrosmalite_Birefringence_1 = 0.0400;

#declare Marialite_IOR_e_1 = 1.537;
#declare Marialite_IOR_w_1 = 1.539;
#declare Marialite_Birefringence_1 = 0.0020;

#declare Mathewrogersite_IOR_e_1 = 1.745;
#declare Mathewrogersite_IOR_w_1 = 1.81;
#declare Mathewrogersite_Birefringence_1 = 0.0650;

#declare Matlockite_IOR_e_1 = 2.04;
#declare Matlockite_IOR_w_1 = 2.15;
#declare Matlockite_Birefringence_1 = 0.1100;

#declare Mattheddleite_IOR_e_1 = 1.999;
#declare Mattheddleite_IOR_w_1 = 2.017;
#declare Mattheddleite_Birefringence_1 = 0.0180;

#declare Mazzite_IOR_e_1 = 1.499;
#declare Mazzite_IOR_w_1 = 1.5062;
#declare Mazzite_Birefringence_1 = 0.0072;

#declare Mcallisterite_IOR_e_1 = 1.459;
#declare Mcallisterite_IOR_w_1 = 1.504;
#declare Mcallisterite_Birefringence_1 = 0.0450;

#declare Mccrillisite_IOR_e_1 = 1.645;
#declare Mccrillisite_IOR_w_1 = 1.634;
#declare Mccrillisite_Birefringence_1 = 0.0110;

#declare Mcgillite_IOR_e_1 = 1.6415;
#declare Mcgillite_IOR_w_1 = 1.6685;
#declare Mcgillite_Birefringence_1 = 0.0270;

#declare Mcgovernite_IOR_e_1 = 1.716;
#declare Mcgovernite_IOR_w_1 = 1.709;
#declare Mcgovernite_Birefringence_1 = 0.0070;

#declare Meionite_IOR_e_1 = 1.55;
#declare Meionite_IOR_e_2 = 1.56;
#declare Meionite_IOR_w_1 = 1.58;
#declare Meionite_IOR_w_2 = 1.6;
#declare Meionite_Birefringence_1 = 0.0300;
#declare Meionite_Birefringence_2 = 0.0400;

#declare Meixnerite_IOR_e_1 = 1.5;
#declare Meixnerite_IOR_w_1 = 1.517;
#declare Meixnerite_Birefringence_1 = 0.0170;

#declare Melanocerite_Ce_IOR_e_1 = 1.72;
#declare Melanocerite_Ce_IOR_w_1 = 1.73;
#declare Melanocerite_Ce_Birefringence_1 = 0.0100;

#declare Melanophlogite_IOR_b_1 = 1.425;

#declare Melanostibite_IOR_w_1 = 2.12;

#declare Melilite_IOR_e_1 = 1.626;
#declare Melilite_IOR_e_2 = 1.658;
#declare Melilite_IOR_w_1 = 1.632;
#declare Melilite_IOR_w_2 = 1.669;
#declare Melilite_Birefringence_1 = 0.0060;
#declare Melilite_Birefringence_2 = 0.0110;

#declare Meliphanite_IOR_e_1 = 1.593;
#declare Meliphanite_IOR_w_1 = 1.612;
#declare Meliphanite_Birefringence_1 = 0.0190;

#declare Mellite_IOR_e_1 = 1.511;
#declare Mellite_IOR_w_1 = 1.539;
#declare Mellite_Birefringence_1 = 0.0280;

#declare Merrihueite_IOR_e_1 = 1.559;
#declare Merrihueite_IOR_e_2 = 1.592;
#declare Merrihueite_IOR_w_1 = 1.57;
#declare Merrihueite_Birefringence_1 = 0.0110;
#declare Merrihueite_Birefringence_2 = 0.0220;

#declare Meta_ankoleite_IOR_e_1 = 1.56;
#declare Meta_ankoleite_IOR_w_1 = 1.58;
#declare Meta_ankoleite_Birefringence_1 = 0.0200;

#declare Meta_autunite_IOR_e_1 = 1.584;
#declare Meta_autunite_IOR_w_1 = 1.607;
#declare Meta_autunite_Birefringence_1 = 0.0230;

#declare Metaheinrichite_IOR_e_1 = 1.609;
#declare Metaheinrichite_IOR_w_1 = 1.637;
#declare Metaheinrichite_Birefringence_1 = 0.0280;

#declare Metakahlerite_IOR_e_1 = 1.608;
#declare Metakahlerite_IOR_w_1 = 1.642;
#declare Metakahlerite_Birefringence_1 = 0.0340;

#declare Metakirchheimerite_IOR_e_1 = 1.617;
#declare Metakirchheimerite_IOR_w_1 = 1.644;
#declare Metakirchheimerite_Birefringence_1 = 0.0270;

#declare Metanovacekite_IOR_e_1 = 1.595;
#declare Metanovacekite_IOR_w_1 = 1.632;
#declare Metanovacekite_Birefringence_1 = 0.0370;

#declare Metatorbernite_IOR_e_1 = 1.626;
#declare Metatorbernite_IOR_w_1 = 1.624;
#declare Metatorbernite_Birefringence_1 = 0.0020;

#declare Metavoltine_IOR_e_1 = 1.57;
#declare Metavoltine_IOR_w_1 = 1.59;
#declare Metavoltine_Birefringence_1 = 0.0200;

#declare Metazeunerite_IOR_e_1 = 1.626;
#declare Metazeunerite_IOR_w_1 = 1.65;
#declare Metazeunerite_Birefringence_1 = 0.0240;

#declare Microsommite_IOR_e_1 = 1.529;
#declare Microsommite_IOR_w_1 = 1.521;
#declare Microsommite_Birefringence_1 = 0.0080;

#declare Mikasaite_IOR_e_1 = 1.518;
#declare Mikasaite_IOR_w_1 = 1.504;
#declare Mikasaite_Birefringence_1 = 0.0140;

#declare Milarite_IOR_e_1 = 1.529;
#declare Milarite_IOR_e_2 = 1.548;
#declare Milarite_IOR_w_1 = 1.532;
#declare Milarite_IOR_w_2 = 1.551;
#declare Milarite_Birefringence_1 = 0.0030;
#declare Milarite_Birefringence_2 = 0.0160;

#declare Millosevichite_IOR_e_1 = 1.515;
#declare Millosevichite_IOR_w_1 = 1.5;
#declare Millosevichite_Birefringence_1 = 0.0150;

#declare Mimetite_IOR_e_1 = 2.129;
#declare Mimetite_IOR_w_1 = 2.144;
#declare Mimetite_Birefringence_1 = 0.0150;

#declare Mineevite_Y_IOR_e_1 = 1.51;
#declare Mineevite_Y_IOR_w_1 = 1.536;
#declare Mineevite_Y_Birefringence_1 = 0.0260;

#declare Minehillite_IOR_e_1 = 1.604;
#declare Minehillite_IOR_w_1 = 1.607;
#declare Minehillite_Birefringence_1 = 0.0030;

#declare Minium_IOR_a_1 = 2.4;

#declare Minrecordite_IOR_e_1 = 1.55;
#declare Minrecordite_IOR_w_1 = 1.75;
#declare Minrecordite_Birefringence_1 = 0.2000;

#declare Mitscherlichite_IOR_e_1 = 1.615;
#declare Mitscherlichite_IOR_w_1 = 1.637;
#declare Mitscherlichite_Birefringence_1 = 0.0220;

#declare Mixite_IOR_e_1 = 1.81;
#declare Mixite_IOR_w_1 = 1.73;
#declare Mixite_Birefringence_1 = 0.0800;

#declare Moissanite_IOR_e_1 = 2.654;
#declare Moissanite_IOR_e_2 = 2.812;
#declare Moissanite_IOR_w_1 = 2.616;
#declare Moissanite_IOR_w_2 = 2.757;
#declare Moissanite_Birefringence_1 = 0.0380;
#declare Moissanite_Birefringence_2 = 0.0550;

#declare Molybdophyllite_IOR_e_1 = 1.761;
#declare Molybdophyllite_IOR_w_1 = 1.815;
#declare Molybdophyllite_Birefringence_1 = 0.0540;

#declare Molysite_IOR_w_1 = 1.6;

#declare Mongolite_IOR_e_1 = 1.74;
#declare Mongolite_IOR_w_1 = 1.8;
#declare Mongolite_Birefringence_1 = 0.0600;

#declare Monohydrocalcite_IOR_e_1 = 1.59;
#declare Monohydrocalcite_IOR_w_1 = 1.545;
#declare Monohydrocalcite_Birefringence_1 = 0.0450;

#declare Mopungite_IOR_e_1 = 1.605;
#declare Mopungite_IOR_w_1 = 1.614;
#declare Mopungite_Birefringence_1 = 0.0090;

#declare Morelandite_IOR_e_1 = 1.884;
#declare Morelandite_IOR_w_1 = 1.88;
#declare Morelandite_Birefringence_1 = 0.0040;

#declare Motukoreaite_IOR_a_1 = 1.51;
#declare Motukoreaite_IOR_b_1 = 1.51;
#declare Motukoreaite_Birefringence_1 = 0.0000;

#declare Mountkeithite_IOR_e_1 = 1.51;
#declare Mountkeithite_IOR_w_1 = 1.52;
#declare Mountkeithite_Birefringence_1 = 0.0100;

#declare Muirite_IOR_e_1 = 1.704;
#declare Muirite_IOR_w_1 = 1.697;
#declare Muirite_Birefringence_1 = 0.0070;

#declare Musgravite_IOR_e_1 = 1.735;
#declare Musgravite_IOR_w_1 = 1.739;
#declare Musgravite_Birefringence_1 = 0.0040;

#declare Nabokoite_IOR_e_1 = 1.773;
#declare Nabokoite_IOR_w_1 = 1.778;
#declare Nabokoite_Birefringence_1 = 0.0050;

#declare Namuwite_IOR_b_1 = 1.577;

#declare Nanlingite_IOR_e_1 = 1.78;
#declare Nanlingite_IOR_w_1 = 1.82;
#declare Nanlingite_Birefringence_1 = 0.0400;

#declare Narsarsukite_IOR_e_1 = 1.63;
#declare Narsarsukite_IOR_w_1 = 1.609;
#declare Narsarsukite_Birefringence_1 = 0.0210;

#declare Nasonite_IOR_e_1 = 1.923;
#declare Nasonite_IOR_w_1 = 1.913;
#declare Nasonite_Birefringence_1 = 0.0100;

#declare Natisite_IOR_e_1 = 1.68;
#declare Natisite_IOR_w_1 = 1.756;
#declare Natisite_Birefringence_1 = 0.0760;

#declare Natroalunite_IOR_e_1 = 1.59;
#declare Natroalunite_IOR_w_1 = 1.568;
#declare Natroalunite_Birefringence_1 = 0.0220;

#declare Natrofairchildite_IOR_e_1 = 1.459;
#declare Natrofairchildite_IOR_w_1 = 1.525;
#declare Natrofairchildite_Birefringence_1 = 0.0660;

#declare Natrojarosite_IOR_e_1 = 1.75;
#declare Natrojarosite_IOR_w_1 = 1.83;
#declare Natrojarosite_Birefringence_1 = 0.0800;

#declare Nepheline_IOR_e_1 = 1.528;
#declare Nepheline_IOR_e_2 = 1.544;
#declare Nepheline_IOR_w_1 = 1.531;
#declare Nepheline_IOR_w_2 = 1.549;
#declare Nepheline_Birefringence_1 = 0.0030;
#declare Nepheline_Birefringence_2 = 0.0050;

#declare Nierite_IOR_e_1 = 2.02;
#declare Nierite_IOR_w_1 = 2.03;
#declare Nierite_Birefringence_1 = 0.0100;

#declare Nigerite_6H_IOR_e_1 = 1.81;
#declare Nigerite_6H_IOR_w_1 = 1.8;
#declare Nigerite_6H_Birefringence_1 = 0.0100;

#declare Nitratine_IOR_e_1 = 1.58;
#declare Nitratine_IOR_e_2 = 1.587;
#declare Nitratine_IOR_w_1 = 1.33;
#declare Nitratine_IOR_w_2 = 1.336;
#declare Nitratine_Birefringence_1 = 0.2500;
#declare Nitratine_Birefringence_2 = 0.2510;

#declare Nordenskioldine_IOR_e_1 = 1.66;
#declare Nordenskioldine_IOR_w_1 = 1.778;
#declare Nordenskioldine_Birefringence_1 = 0.1180;

#declare Norsethite_IOR_e_1 = 1.519;
#declare Norsethite_IOR_w_1 = 1.694;
#declare Norsethite_Birefringence_1 = 0.1750;

#declare Novacekite_IOR_e_1 = 1.62;
#declare Novacekite_IOR_e_2 = 1.625;
#declare Novacekite_IOR_w_1 = 1.62;
#declare Novacekite_IOR_w_2 = 1.641;
#declare Novacekite_Birefringence_1 = 0.0000;
#declare Novacekite_Birefringence_2 = 0.0160;

#declare Offretite_IOR_e_1 = 1.486;
#declare Offretite_IOR_w_1 = 1.489;
#declare Offretite_Birefringence_1 = 0.0030;

#declare Okanoganite_Y_IOR_e_1 = 1.74;
#declare Okanoganite_Y_IOR_w_1 = 1.753;
#declare Okanoganite_Y_Birefringence_1 = 0.0130;

#declare Okayamalite_IOR_e_1 = 1.67;
#declare Okayamalite_IOR_w_1 = 1.7;
#declare Okayamalite_Birefringence_1 = 0.0300;

#declare Olekminskite_IOR_e_1 = 1.527;
#declare Olekminskite_IOR_w_1 = 1.67;
#declare Olekminskite_Birefringence_1 = 0.1430;

#declare Olenite_IOR_e_1 = 1.635;
#declare Olenite_IOR_w_1 = 1.654;
#declare Olenite_Birefringence_1 = 0.0190;

#declare Olgite_IOR_e_1 = 1.619;
#declare Olgite_IOR_w_1 = 1.623;
#declare Olgite_Birefringence_1 = 0.0040;

#declare Orebroite_III_IOR_e_1 = 1.875;
#declare Orebroite_III_IOR_w_1 = 1.857;
#declare Orebroite_III_Birefringence_1 = 0.0180;

#declare Orebroite_VIII_IOR_e_1 = 1.875;
#declare Orebroite_VIII_IOR_w_1 = 1.857;
#declare Orebroite_VIII_Birefringence_1 = 0.0180;

#declare Orlymanite_IOR_w_1 = 1.598;

#declare Orpheite_IOR_e_1 = 1.691;
#declare Orpheite_IOR_w_1 = 1.67;
#declare Orpheite_Birefringence_1 = 0.0210;

#declare Orschallite_IOR_e_1 = 1.496;
#declare Orschallite_IOR_w_1 = 1.4941;
#declare Orschallite_Birefringence_1 = 0.0019;

#declare Osarizawaite_IOR_e_1 = 1.731;
#declare Osarizawaite_IOR_w_1 = 1.714;
#declare Osarizawaite_Birefringence_1 = 0.0170;

#declare Osumilite_Fe_IOR_e_1 = 1.549;
#declare Osumilite_Fe_IOR_e_2 = 1.551;
#declare Osumilite_Fe_IOR_w_1 = 1.545;
#declare Osumilite_Fe_IOR_w_2 = 1.547;
#declare Osumilite_Fe_Birefringence_1 = 0.0040;

#declare Osumilite_Mg_IOR_e_1 = 1.543;
#declare Osumilite_Mg_IOR_w_1 = 1.5406;
#declare Osumilite_Mg_Birefringence_1 = 0.0024;

#declare Pabstite_IOR_e_1 = 1.674;
#declare Pabstite_IOR_w_1 = 1.685;
#declare Pabstite_Birefringence_1 = 0.0110;

#declare Painite_IOR_e_1 = 1.7875;
#declare Painite_IOR_w_1 = 1.8159;
#declare Painite_Birefringence_1 = 0.0284;

#declare Palmierite_IOR_w_1 = 1.712;

#declare Panunzite_IOR_e_1 = 1.535;
#declare Panunzite_IOR_w_1 = 1.54;
#declare Panunzite_Birefringence_1 = 0.0050;

#declare Paracoquimbite_IOR_e_1 = 1.555;
#declare Paracoquimbite_IOR_w_1 = 1.55;
#declare Paracoquimbite_Birefringence_1 = 0.0050;

#declare Parakhinite_IOR_e_1 = 2.12;
#declare Parakhinite_IOR_w_1 = 2.155;
#declare Parakhinite_Birefringence_1 = 0.0350;

#declare Paralstonite_IOR_e_1 = 1.527;
#declare Paralstonite_IOR_w_1 = 1.672;
#declare Paralstonite_Birefringence_1 = 0.1450;

#declare Paraniite_Y_IOR_e_1 = 1.92;
#declare Paraniite_Y_IOR_w_1 = 1.87;
#declare Paraniite_Y_Birefringence_1 = 0.0500;

#declare Paratacamite_IOR_e_1 = 1.848;
#declare Paratacamite_IOR_w_1 = 1.842;
#declare Paratacamite_Birefringence_1 = 0.0060;

#declare Parisite_Ce_IOR_e_1 = 1.757;
#declare Parisite_Ce_IOR_w_1 = 1.676;
#declare Parisite_Ce_Birefringence_1 = 0.0810;

#declare Parisite_Nd_IOR_e_1 = 1.754;
#declare Parisite_Nd_IOR_w_1 = 1.679;
#declare Parisite_Nd_Birefringence_1 = 0.0750;

#declare Parkinsonite_IOR_e_1 = 2.42;
#declare Parkinsonite_IOR_w_1 = 2.58;
#declare Parkinsonite_Birefringence_1 = 0.1600;

#declare Pehrmanite_IOR_w_1 = 1.79;

#declare Penfieldite_IOR_e_1 = 2.21;
#declare Penfieldite_IOR_w_1 = 2.13;
#declare Penfieldite_Birefringence_1 = 0.0800;

#declare Pengzhizhongite_24R_IOR_e_1 = 1.814;
#declare Pengzhizhongite_24R_IOR_w_1 = 1.802;
#declare Pengzhizhongite_24R_Birefringence_1 = 0.0120;

#declare Pengzhizhongite_6H_IOR_e_1 = 1.814;
#declare Pengzhizhongite_6H_IOR_w_1 = 1.802;
#declare Pengzhizhongite_6H_Birefringence_1 = 0.0120;

#declare Peprossiite_Ce_IOR_e_1 = 1.711;
#declare Peprossiite_Ce_IOR_w_1 = 1.703;
#declare Peprossiite_Ce_Birefringence_1 = 0.0080;

#declare Perhamite_IOR_e_1 = 1.577;
#declare Perhamite_IOR_w_1 = 1.564;
#declare Perhamite_Birefringence_1 = 0.0130;

#declare Petersite_Y_IOR_e_1 = 1.747;
#declare Petersite_Y_IOR_w_1 = 1.666;
#declare Petersite_Y_Birefringence_1 = 0.0810;

#declare Phenakite_IOR_e_1 = 1.67;
#declare Phenakite_IOR_w_1 = 1.654;
#declare Phenakite_Birefringence_1 = 0.0160;

#declare Philipsbornite_IOR_a_1 = 1.79;
#declare Philipsbornite_IOR_b_1 = 1.79;
#declare Philipsbornite_Birefringence_1 = 0.0000;

#declare Phosgenite_IOR_e_1 = 2.14;
#declare Phosgenite_IOR_w_1 = 2.114;
#declare Phosgenite_Birefringence_1 = 0.0260;

#declare Phosphoellenbergerite_IOR_e_1 = 1.588;
#declare Phosphoellenbergerite_IOR_e_2 = 1.589;
#declare Phosphoellenbergerite_IOR_w_1 = 1.606;
#declare Phosphoellenbergerite_IOR_w_2 = 1.609;
#declare Phosphoellenbergerite_Birefringence_1 = 0.0180;
#declare Phosphoellenbergerite_Birefringence_2 = 0.0200;

#declare Pinnoite_IOR_e_1 = 1.575;
#declare Pinnoite_IOR_w_1 = 1.565;
#declare Pinnoite_Birefringence_1 = 0.0100;

#declare Pitaglianoite_IOR_e_1 = 1.506;
#declare Pitaglianoite_IOR_w_1 = 1.508;
#declare Pitaglianoite_Birefringence_1 = 0.0020;

#declare Piypite_IOR_e_1 = 1.695;
#declare Piypite_IOR_w_1 = 1.583;
#declare Piypite_Birefringence_1 = 0.1120;

#declare Plattnerite_IOR_e_1 = 2.25;
#declare Plattnerite_IOR_w_1 = 2.35;
#declare Plattnerite_Birefringence_1 = 0.1000;

#declare Plumbogummite_IOR_e_1 = 1.675;
#declare Plumbogummite_IOR_w_1 = 1.653;
#declare Plumbogummite_Birefringence_1 = 0.0220;

#declare Plumbojarosite_IOR_e_1 = 1.783;
#declare Plumbojarosite_IOR_w_1 = 1.878;
#declare Plumbojarosite_Birefringence_1 = 0.0950;

#declare Portlandite_IOR_e_1 = 1.547;
#declare Portlandite_IOR_w_1 = 1.574;
#declare Portlandite_Birefringence_1 = 0.0270;

#declare Pottsite_IOR_e_1 = 2.3;
#declare Pottsite_IOR_w_1 = 2.4;
#declare Pottsite_Birefringence_1 = 0.1000;

#declare Povondraite_IOR_e_1 = 1.751;
#declare Povondraite_IOR_w_1 = 1.82;
#declare Povondraite_Birefringence_1 = 0.0690;

#declare Powellite_IOR_e_1 = 1.984;
#declare Powellite_IOR_w_1 = 1.974;
#declare Powellite_Birefringence_1 = 0.0100;

#declare Pretulite_IOR_e_1 = 1.86;
#declare Pretulite_IOR_w_1 = 1.709;
#declare Pretulite_Birefringence_1 = 0.1510;

#declare Proustite_IOR_e_1 = 2.792;
#declare Proustite_IOR_w_1 = 3.087;
#declare Proustite_IOR_w_2 = 3.088;
#declare Proustite_Birefringence_1 = 0.2950;
#declare Proustite_Birefringence_2 = 0.2960;

#declare Pseudoboleite_IOR_e_1 = 2;
#declare Pseudoboleite_IOR_w_1 = 2.03;
#declare Pseudoboleite_Birefringence_1 = 0.0300;

#declare Pyatenkoite_Y_IOR_e_1 = 1.607;
#declare Pyatenkoite_Y_IOR_w_1 = 1.612;
#declare Pyatenkoite_Y_Birefringence_1 = 0.0050;

#declare Pyrargyrite_IOR_e_1 = 2.881;
#declare Pyrargyrite_IOR_w_1 = 3.084;
#declare Pyrargyrite_Birefringence_1 = 0.2030;

#declare Pyroaurite_IOR_e_1 = 1.543;
#declare Pyroaurite_IOR_w_1 = 1.564;
#declare Pyroaurite_Birefringence_1 = 0.0210;

#declare Pyrochroite_IOR_e_1 = 1.72;
#declare Pyrochroite_IOR_e_2 = 1.723;
#declare Pyrochroite_IOR_w_1 = 1.68;
#declare Pyrochroite_IOR_w_2 = 1.681;
#declare Pyrochroite_Birefringence_1 = 0.0400;
#declare Pyrochroite_Birefringence_2 = 0.0420;

#declare Pyromorphite_IOR_e_1 = 2.049;
#declare Pyromorphite_IOR_w_1 = 2.059;
#declare Pyromorphite_Birefringence_1 = 0.0100;

#declare Pyrophanite_IOR_e_1 = 2.21;
#declare Pyrophanite_IOR_w_1 = 2.481;
#declare Pyrophanite_Birefringence_1 = 0.2710;

#declare Quadridavyne_IOR_e_1 = 1.532;
#declare Quadridavyne_IOR_w_1 = 1.529;
#declare Quadridavyne_Birefringence_1 = 0.0030;

#declare Quartz_IOR_e_1 = 1.552;
#declare Quartz_IOR_e_2 = 1.554;
#declare Quartz_IOR_w_1 = 1.543;
#declare Quartz_IOR_w_2 = 1.545;
#declare Quartz_Birefringence_1 = 0.0090;

#declare Quetzalcoatlite_IOR_e_1 = 1.74;
#declare Quetzalcoatlite_IOR_w_1 = 1.802;
#declare Quetzalcoatlite_Birefringence_1 = 0.0620;

#declare Quintinite_2H_IOR_e_1 = 1.533;
#declare Quintinite_2H_IOR_w_1 = 1.533;
#declare Quintinite_2H_Birefringence_1 = 0.0000;

#declare Quintinite_3T_IOR_a_1 = 1.533;
#declare Quintinite_3T_IOR_b_1 = 1.533;
#declare Quintinite_3T_Birefringence_1 = 0.0000;

#declare Rambergite_IOR_a_1 = 2.62;
#declare Rambergite_IOR_a_2 = 2.77;
#declare Rambergite_IOR_b_1 = 2.62;
#declare Rambergite_IOR_b_2 = 2.77;
#declare Rambergite_Birefringence_1 = 0.0000;

#declare Reederite_Y_IOR_e_1 = 1.537;
#declare Reederite_Y_IOR_w_1 = 1.548;
#declare Reederite_Y_Birefringence_1 = 0.0110;

#declare Reevesite_IOR_e_1 = 1.65;
#declare Reevesite_IOR_w_1 = 1.735;
#declare Reevesite_Birefringence_1 = 0.0850;

#declare Retgersite_IOR_e_1 = 1.4873;
#declare Retgersite_IOR_w_1 = 1.5109;
#declare Retgersite_Birefringence_1 = 0.0236;

#declare Reyerite_IOR_e_1 = 1.558;
#declare Reyerite_IOR_w_1 = 1.563;
#declare Reyerite_Birefringence_1 = 0.0050;

#declare Rhabdophane_Ce_IOR_e_1 = 1.744;
#declare Rhabdophane_Ce_IOR_w_1 = 1.688;
#declare Rhabdophane_Ce_Birefringence_1 = 0.0560;

#declare Rhabdophane_La_IOR_e_1 = 1.703;
#declare Rhabdophane_La_IOR_w_1 = 1.654;
#declare Rhabdophane_La_Birefringence_1 = 0.0490;

#declare Rhodochrosite_IOR_e_1 = 1.596;
#declare Rhodochrosite_IOR_e_2 = 1.598;
#declare Rhodochrosite_IOR_w_1 = 1.814;
#declare Rhodochrosite_IOR_w_2 = 1.816;
#declare Rhodochrosite_Birefringence_1 = 0.2180;

#declare Rinneite_IOR_e_1 = 1.5894;
#declare Rinneite_IOR_w_1 = 1.5886;
#declare Rinneite_Birefringence_1 = 0.0008;

#declare Roedderite_IOR_e_1 = 1.542;
#declare Roedderite_IOR_w_1 = 1.537;
#declare Roedderite_Birefringence_1 = 0.0050;

#declare Roggianite_IOR_e_1 = 1.535;
#declare Roggianite_IOR_w_1 = 1.527;
#declare Roggianite_Birefringence_1 = 0.0080;

#declare Rontgenite_Ce_IOR_e_1 = 1.756;
#declare Rontgenite_Ce_IOR_w_1 = 1.662;
#declare Rontgenite_Ce_Birefringence_1 = 0.0940;

#declare Rorisite_IOR_e_1 = 1.635;
#declare Rorisite_IOR_w_1 = 1.668;
#declare Rorisite_Birefringence_1 = 0.0330;

#declare Rosenbergite_IOR_e_1 = 1.403;
#declare Rosenbergite_IOR_w_1 = 1.427;
#declare Rosenbergite_Birefringence_1 = 0.0240;

#declare Rosiaite_IOR_e_1 = 1.92;
#declare Rosiaite_IOR_w_1 = 2.092;
#declare Rosiaite_Birefringence_1 = 0.1720;

#declare Rossmanite_IOR_e_1 = 1.624;
#declare Rossmanite_IOR_w_1 = 1.645;
#declare Rossmanite_Birefringence_1 = 0.0210;

#declare Rutile_IOR_e_1 = 2.908;
#declare Rutile_IOR_w_1 = 2.621;
#declare Rutile_Birefringence_1 = 0.2870;

#declare Sabelliite_IOR_e_1 = 1.797;
#declare Sabelliite_IOR_w_1 = 1.802;
#declare Sabelliite_Birefringence_1 = 0.0050;

#declare Sabieite_IOR_e_1 = 1.595;
#declare Sabieite_IOR_w_1 = 1.578;
#declare Sabieite_Birefringence_1 = 0.0170;

#declare Sacrofanite_IOR_e_1 = 1.486;
#declare Sacrofanite_IOR_w_1 = 1.505;
#declare Sacrofanite_Birefringence_1 = 0.0190;

#declare Saleeite_IOR_e_1 = 1.544;
#declare Saleeite_IOR_e_2 = 1.565;
#declare Saleeite_IOR_w_1 = 1.571;
#declare Saleeite_IOR_w_2 = 1.585;
#declare Saleeite_Birefringence_1 = 0.0200;
#declare Saleeite_Birefringence_2 = 0.0270;

#declare Santanaite_IOR_e_1 = 2.12;
#declare Santanaite_IOR_w_1 = 2.32;
#declare Santanaite_Birefringence_1 = 0.2000;

#declare Sarcolite_IOR_e_1 = 1.615;
#declare Sarcolite_IOR_w_1 = 1.604;
#declare Sarcolite_Birefringence_1 = 0.0110;

#declare Saryarkite_Y_IOR_e_1 = 1.62;
#declare Saryarkite_Y_IOR_w_1 = 1.606;
#declare Saryarkite_Y_Birefringence_1 = 0.0140;

#declare Satterlyite_IOR_e_1 = 1.719;
#declare Satterlyite_IOR_w_1 = 1.721;
#declare Satterlyite_Birefringence_1 = 0.0020;

#declare Sazykinaite_Y_IOR_e_1 = 1.578;
#declare Sazykinaite_Y_IOR_w_1 = 1.585;
#declare Sazykinaite_Y_Birefringence_1 = 0.0070;

#declare Scacchite_IOR_e_1 = 1.622;
#declare Scacchite_IOR_w_1 = 1.708;
#declare Scacchite_Birefringence_1 = 0.0860;

#declare Scapolite_IOR_e_1 = 1.522;
#declare Scapolite_IOR_e_2 = 1.571;
#declare Scapolite_IOR_w_1 = 1.534;
#declare Scapolite_IOR_w_2 = 1.607;
#declare Scapolite_Birefringence_1 = 0.0120;
#declare Scapolite_Birefringence_2 = 0.0360;

#declare Schairerite_IOR_e_1 = 1.445;
#declare Schairerite_IOR_w_1 = 1.44;
#declare Schairerite_Birefringence_1 = 0.0050;

#declare Schallerite_IOR_e_1 = 1.679;
#declare Schallerite_IOR_w_1 = 1.704;
#declare Schallerite_Birefringence_1 = 0.0250;

#declare Schaurteite_IOR_e_1 = 1.581;
#declare Schaurteite_IOR_w_1 = 1.569;
#declare Schaurteite_Birefringence_1 = 0.0120;

#declare Scheelite_IOR_e_1 = 1.934;
#declare Scheelite_IOR_e_2 = 1.937;
#declare Scheelite_IOR_w_1 = 1.918;
#declare Scheelite_IOR_w_2 = 1.92;
#declare Scheelite_Birefringence_1 = 0.0160;
#declare Scheelite_Birefringence_2 = 0.0170;

#declare Schlossmacherite_IOR_e_1 = 1.597;

#declare Schorl_IOR_e_1 = 1.633;
#declare Schorl_IOR_e_2 = 1.64;
#declare Schorl_IOR_w_1 = 1.66;
#declare Schorl_IOR_w_2 = 1.672;
#declare Schorl_Birefringence_1 = 0.0270;
#declare Schorl_Birefringence_2 = 0.0320;

#declare Schulenbergite_IOR_e_1 = 1.623;
#declare Schulenbergite_IOR_w_1 = 1.64;
#declare Schulenbergite_Birefringence_1 = 0.0170;

#declare Segnitite_IOR_e_1 = 1.955;
#declare Segnitite_IOR_w_1 = 1.975;
#declare Segnitite_Birefringence_1 = 0.0200;

#declare Sellaite_IOR_e_1 = 1.39;
#declare Sellaite_IOR_w_1 = 1.378;
#declare Sellaite_Birefringence_1 = 0.0120;

#declare Selwynite_IOR_e_1 = 1.636;
#declare Selwynite_IOR_w_1 = 1.624;
#declare Selwynite_Birefringence_1 = 0.0120;

#declare Sergeevite_IOR_b_1 = 1.581;

#declare Shafranovskite_IOR_e_1 = 1.57;
#declare Shafranovskite_IOR_w_1 = 1.587;
#declare Shafranovskite_Birefringence_1 = 0.0170;

#declare Sheldrickite_IOR_e_1 = 1.563;
#declare Sheldrickite_IOR_w_1 = 1.538;
#declare Sheldrickite_Birefringence_1 = 0.0250;

#declare Sherwoodite_IOR_e_1 = 1.735;
#declare Sherwoodite_IOR_w_1 = 1.765;
#declare Sherwoodite_Birefringence_1 = 0.0300;

#declare Shigaite_IOR_w_1 = 1.546;

#declare Siderite_IOR_e_1 = 1.57;
#declare Siderite_IOR_e_2 = 1.633;
#declare Siderite_IOR_w_1 = 1.785;
#declare Siderite_IOR_w_2 = 1.788;
#declare Siderite_Birefringence_1 = 0.1550;
#declare Siderite_Birefringence_2 = 0.2150;

#declare Simonkolleite_IOR_e_1 = 1.7;
#declare Simonkolleite_IOR_w_1 = 1.657;
#declare Simonkolleite_Birefringence_1 = 0.0430;

#declare Simpsonite_IOR_e_1 = 1.976;
#declare Simpsonite_IOR_w_1 = 2.034;
#declare Simpsonite_Birefringence_1 = 0.0580;

#declare Sincosite_IOR_e_1 = 1.655;
#declare Sincosite_IOR_w_1 = 1.68;
#declare Sincosite_Birefringence_1 = 0.0250;

#declare Sitinakite_IOR_e_1 = 1.988;
#declare Sitinakite_IOR_w_1 = 1.78;
#declare Sitinakite_Birefringence_1 = 0.2080;

#declare Sjogrenite_IOR_e_1 = 1.55;
#declare Sjogrenite_IOR_w_1 = 1.573;
#declare Sjogrenite_Birefringence_1 = 0.0230;

#declare Slavikite_IOR_e_1 = 1.506;
#declare Slavikite_IOR_w_1 = 1.53;
#declare Slavikite_Birefringence_1 = 0.0240;

#declare Smithsonite_IOR_e_1 = 1.625;
#declare Smithsonite_IOR_w_1 = 1.85;
#declare Smithsonite_Birefringence_1 = 0.2250;

#declare Sodium_meta_autunite_IOR_e_1 = 1.559;
#declare Sodium_meta_autunite_IOR_w_1 = 1.578;
#declare Sodium_meta_autunite_Birefringence_1 = 0.0190;

#declare Sodium_autunite_IOR_e_1 = 1.559;
#declare Sodium_autunite_IOR_w_1 = 1.578;
#declare Sodium_autunite_Birefringence_1 = 0.0190;

#declare Sodium_uranospinite_IOR_e_1 = 1.585;
#declare Sodium_uranospinite_IOR_w_1 = 1.612;
#declare Sodium_uranospinite_Birefringence_1 = 0.0270;

#declare Sogdianite_IOR_e_1 = 1.606;
#declare Sogdianite_IOR_w_1 = 1.608;
#declare Sogdianite_Birefringence_1 = 0.0020;

#declare Spangolite_IOR_e_1 = 1.641;
#declare Spangolite_IOR_w_1 = 1.694;
#declare Spangolite_Birefringence_1 = 0.0530;

#declare Sphaerobismoite_IOR_e_1 = 2.18;
#declare Sphaerobismoite_IOR_w_1 = 2.13;
#declare Sphaerobismoite_Birefringence_1 = 0.0500;

#declare Sphaerocobaltite_IOR_e_1 = 1.6;
#declare Sphaerocobaltite_IOR_w_1 = 1.885;
#declare Sphaerocobaltite_Birefringence_1 = 0.2850;

#declare Stanekite_IOR_a_1 = 2.01;
#declare Stanekite_IOR_b_1 = 2.11;
#declare Stanekite_Birefringence_1 = 0.1000;

#declare Steacyite_IOR_e_1 = 1.572;
#declare Steacyite_IOR_w_1 = 1.573;
#declare Steacyite_Birefringence_1 = 0.0010;

#declare Steenstrupine_Ce_IOR_e_1 = 1.663;
#declare Steenstrupine_Ce_IOR_w_1 = 1.665;
#declare Steenstrupine_Ce_Birefringence_1 = 0.0020;

#declare Stepanovite_IOR_e_1 = 1.417;
#declare Stepanovite_IOR_w_1 = 1.515;
#declare Stepanovite_Birefringence_1 = 0.0980;

#declare Stichtite_IOR_e_1 = 1.542;
#declare Stichtite_IOR_w_1 = 1.516;
#declare Stichtite_Birefringence_1 = 0.0260;

#declare Stillwellite_Ce_IOR_e_1 = 1.78;
#declare Stillwellite_Ce_IOR_w_1 = 1.765;
#declare Stillwellite_Ce_Birefringence_1 = 0.0150;

#declare Stishovite_IOR_e_1 = 1.826;
#declare Stishovite_IOR_w_1 = 1.799;
#declare Stishovite_Birefringence_1 = 0.0270;

#declare Stolzite_IOR_e_1 = 2.19;
#declare Stolzite_IOR_w_1 = 2.27;
#declare Stolzite_Birefringence_1 = 0.0800;

#declare Stoppaniite_IOR_e_1 = 1.619;
#declare Stoppaniite_IOR_w_1 = 1.625;
#declare Stoppaniite_Birefringence_1 = 0.0060;

#declare Stottite_IOR_e_1 = 1.728;
#declare Stottite_IOR_w_1 = 1.738;
#declare Stottite_Birefringence_1 = 0.0100;

#declare Stratlingite_IOR_w_1 = 1.534;

#declare Strontiowhitlockite_IOR_e_1 = 1.598;
#declare Strontiowhitlockite_IOR_w_1 = 1.601;
#declare Strontiowhitlockite_Birefringence_1 = 0.0030;

#declare Strontium_apatite_IOR_e_1 = 1.637;
#declare Strontium_apatite_IOR_w_1 = 1.651;
#declare Strontium_apatite_Birefringence_1 = 0.0140;

#declare Sturmanite_IOR_e_1 = 1.505;
#declare Sturmanite_IOR_w_1 = 1.5;
#declare Sturmanite_Birefringence_1 = 0.0050;

#declare Sugilite_IOR_e_1 = 1.607;
#declare Sugilite_IOR_w_1 = 1.61;
#declare Sugilite_Birefringence_1 = 0.0030;

#declare Svabite_IOR_e_1 = 1.698;
#declare Svabite_IOR_w_1 = 1.706;
#declare Svabite_Birefringence_1 = 0.0080;

#declare Svanbergite_IOR_e_1 = 1.646;
#declare Svanbergite_IOR_w_1 = 1.631;
#declare Svanbergite_Birefringence_1 = 0.0150;

#declare Swedenborgite_IOR_e_1 = 1.77;
#declare Swedenborgite_IOR_w_1 = 1.772;
#declare Swedenborgite_Birefringence_1 = 0.0020;

#declare Sweetite_IOR_e_1 = 1.628;
#declare Sweetite_IOR_w_1 = 1.635;
#declare Sweetite_Birefringence_1 = 0.0070;

#declare Szymanskiite_IOR_e_1 = 1.786;
#declare Szymanskiite_IOR_w_1 = 1.795;
#declare Szymanskiite_Birefringence_1 = 0.0090;

#declare Tachyhydrite_IOR_e_1 = 1.512;
#declare Tachyhydrite_IOR_w_1 = 1.52;
#declare Tachyhydrite_Birefringence_1 = 0.0080;

#declare Takedaite_IOR_e_1 = 1.63;
#declare Takedaite_IOR_w_1 = 1.726;
#declare Takedaite_Birefringence_1 = 0.0960;

#declare Takovite_IOR_e_1 = 1.6;
#declare Takovite_IOR_w_1 = 1.601;
#declare Takovite_IOR_w_2 = 1.602;
#declare Takovite_Birefringence_1 = 0.0010;
#declare Takovite_Birefringence_2 = 0.0020;

#declare Teepleite_IOR_e_1 = 1.503;
#declare Teepleite_IOR_w_1 = 1.519;
#declare Teepleite_Birefringence_1 = 0.0160;

#declare Tetranatrolite_IOR_e_1 = 1.496;
#declare Tetranatrolite_IOR_w_1 = 1.481;
#declare Tetranatrolite_Birefringence_1 = 0.0150;

#declare Tetrarooseveltite_IOR_e_1 = 2.2;
#declare Tetrarooseveltite_IOR_w_1 = 2.2;
#declare Tetrarooseveltite_Birefringence_1 = 0.0000;

#declare Tetrawickmanite_IOR_e_1 = 1.72;
#declare Tetrawickmanite_IOR_w_1 = 1.724;
#declare Tetrawickmanite_Birefringence_1 = 0.0040;

#declare Thaumasite_IOR_e_1 = 1.468;
#declare Thaumasite_IOR_w_1 = 1.507;
#declare Thaumasite_Birefringence_1 = 0.0390;

#declare Theophrastite_IOR_e_1 = 1.759;
#declare Theophrastite_IOR_e_2 = 1.76;
#declare Theophrastite_IOR_w_1 = 1.759;
#declare Theophrastite_IOR_w_2 = 1.76;
#declare Theophrastite_Birefringence_1 = 0.0000;

#declare Theresemagnanite_IOR_e_1 = 1.542;
#declare Theresemagnanite_IOR_w_1 = 1.568;
#declare Theresemagnanite_Birefringence_1 = 0.0260;

#declare Thorbastnasite_IOR_e_1 = 1.67;
#declare Thorbastnasite_IOR_e_2 = 1.678;

#declare Thorite_IOR_e_1 = 1.78;
#declare Thorite_IOR_e_2 = 1.82;
#declare Thorite_IOR_w_1 = 1.79;
#declare Thorite_IOR_w_2 = 1.84;
#declare Thorite_Birefringence_1 = 0.0100;
#declare Thorite_Birefringence_2 = 0.0200;

#declare Thornasite_IOR_e_1 = 1.512;
#declare Thornasite_IOR_w_1 = 1.51;
#declare Thornasite_Birefringence_1 = 0.0020;

#declare Tienshanite_IOR_e_1 = 1.653;
#declare Tienshanite_IOR_w_1 = 1.666;
#declare Tienshanite_Birefringence_1 = 0.0130;

#declare Tincalconite_IOR_e_1 = 1.47;
#declare Tincalconite_IOR_w_1 = 1.46;
#declare Tincalconite_Birefringence_1 = 0.0100;

#declare Tiptopite_IOR_e_1 = 1.559;
#declare Tiptopite_IOR_w_1 = 1.551;
#declare Tiptopite_Birefringence_1 = 0.0080;

#declare Tisinalite_IOR_e_1 = 1.59;
#declare Tisinalite_IOR_e_2 = 1.592;
#declare Tisinalite_IOR_w_1 = 1.624;
#declare Tisinalite_Birefringence_1 = 0.0320;
#declare Tisinalite_Birefringence_2 = 0.0340;

#declare Torbernite_IOR_e_1 = 1.582;
#declare Torbernite_IOR_w_1 = 1.592;
#declare Torbernite_Birefringence_1 = 0.0100;

#declare Tounkite_IOR_e_1 = 1.543;
#declare Tounkite_IOR_w_1 = 1.528;
#declare Tounkite_Birefringence_1 = 0.0150;

#declare Traskite_IOR_e_1 = 1.702;
#declare Traskite_IOR_w_1 = 1.714;
#declare Traskite_Birefringence_1 = 0.0120;

#declare Trechmannite_IOR_e_1 = 2.4;
#declare Trechmannite_IOR_w_1 = 2.6;
#declare Trechmannite_Birefringence_1 = 0.2000;

#declare Trembathite_IOR_e_1 = 1.668;
#declare Trembathite_IOR_w_1 = 1.684;
#declare Trembathite_Birefringence_1 = 0.0160;

#declare Trippkeite_IOR_e_1 = 2.12;
#declare Trippkeite_IOR_w_1 = 1.9;
#declare Trippkeite_Birefringence_1 = 0.2200;

#declare Tripuhyite_IOR_e_1 = 2.33;
#declare Tripuhyite_IOR_w_1 = 2.19;
#declare Tripuhyite_Birefringence_1 = 0.1400;

#declare Tristramite_IOR_e_1 = 1.664;
#declare Tristramite_IOR_w_1 = 1.644;
#declare Tristramite_Birefringence_1 = 0.0200;

#declare Trogerite_IOR_e_1 = 1.584;
#declare Trogerite_IOR_w_1 = 1.612;
#declare Trogerite_Birefringence_1 = 0.0280;

#declare Tschernichite_IOR_e_1 = 1.483;
#declare Tschernichite_IOR_w_1 = 1.484;
#declare Tschernichite_Birefringence_1 = 0.0010;

#declare Tugtupite_IOR_e_1 = 1.502;
#declare Tugtupite_IOR_w_1 = 1.496;
#declare Tugtupite_Birefringence_1 = 0.0060;

#declare Tuliokite_IOR_e_1 = 1.587;
#declare Tuliokite_IOR_w_1 = 1.574;
#declare Tuliokite_Birefringence_1 = 0.0130;

#declare Tungusite_IOR_w_1 = 1.586;

#declare Tunisite_IOR_e_1 = 1.599;
#declare Tunisite_IOR_w_1 = 1.573;
#declare Tunisite_Birefringence_1 = 0.0260;

#declare Turkestanite_IOR_e_1 = 1.606;
#declare Turkestanite_IOR_w_1 = 1.611;
#declare Turkestanite_Birefringence_1 = 0.0050;

#declare Turneaureite_IOR_e_1 = 1.7;
#declare Turneaureite_IOR_w_1 = 1.708;
#declare Turneaureite_Birefringence_1 = 0.0080;

#declare Tusionite_IOR_e_1 = 1.752;
#declare Tusionite_IOR_w_1 = 1.854;
#declare Tusionite_Birefringence_1 = 0.1020;

#declare Taaffeite_IOR_e_1 = 1.777;
#declare Taaffeite_IOR_w_1 = 1.722;
#declare Taaffeite_Birefringence_1 = 0.0550;

#declare Ungemachite_IOR_e_1 = 1.502;
#declare Ungemachite_IOR_w_1 = 1.449;
#declare Ungemachite_Birefringence_1 = 0.0530;

#declare Uranospinite_IOR_e_1 = 1.55;
#declare Uranospinite_IOR_e_2 = 1.596;
#declare Uranospinite_IOR_w_1 = 1.572;
#declare Uranospinite_IOR_w_2 = 1.621;
#declare Uranospinite_Birefringence_1 = 0.0220;
#declare Uranospinite_Birefringence_2 = 0.0250;

#declare Urea_IOR_e_1 = 1.603;
#declare Urea_IOR_w_1 = 1.484;
#declare Urea_Birefringence_1 = 0.1190;

#declare Uvite_IOR_e_1 = 1.65;
#declare Uvite_IOR_w_1 = 1.67;
#declare Uvite_Birefringence_1 = 0.0200;

#declare Vanadinite_IOR_e_1 = 2.35;
#declare Vanadinite_IOR_w_1 = 2.416;
#declare Vanadinite_Birefringence_1 = 0.0660;

#declare Vaterite_IOR_e_1 = 1.65;
#declare Vaterite_IOR_w_1 = 1.55;
#declare Vaterite_Birefringence_1 = 0.1000;

#declare Verplanckite_IOR_e_1 = 1.672;
#declare Verplanckite_IOR_w_1 = 1.683;
#declare Verplanckite_Birefringence_1 = 0.0110;

#declare Vesuvianite_IOR_e_1 = 1.698;
#declare Vesuvianite_IOR_e_2 = 1.736;
#declare Vesuvianite_IOR_w_1 = 1.702;
#declare Vesuvianite_IOR_w_2 = 1.742;
#declare Vesuvianite_Birefringence_1 = 0.0040;
#declare Vesuvianite_Birefringence_2 = 0.0060;

#declare Vicanite_Ce_IOR_e_1 = 1.722;
#declare Vicanite_Ce_IOR_w_1 = 1.757;
#declare Vicanite_Ce_Birefringence_1 = 0.0350;

#declare Virgilite_IOR_w_1 = 1.52;

#declare Vishnevite_IOR_e_1 = 1.488;
#declare Vishnevite_IOR_e_2 = 1.511;
#declare Vishnevite_IOR_w_1 = 1.49;
#declare Vishnevite_IOR_w_2 = 1.507;
#declare Vishnevite_Birefringence_1 = 0.0020;
#declare Vishnevite_Birefringence_2 = 0.0040;

#declare Vlodavetsite_IOR_e_1 = 1.526;
#declare Vlodavetsite_IOR_w_1 = 1.509;
#declare Vlodavetsite_Birefringence_1 = 0.0170;

#declare Wadeite_IOR_e_1 = 1.655;
#declare Wadeite_IOR_w_1 = 1.625;
#declare Wadeite_Birefringence_1 = 0.0300;

#declare Wakefieldite_Y_IOR_e_1 = 2.14;
#declare Wakefieldite_Y_IOR_w_1 = 2;
#declare Wakefieldite_Y_Birefringence_1 = 0.1400;

#declare Wallkilldellite_IOR_w_1 = 1.728;

#declare Wallkilldellite_Fe_IOR_w_1 = 1.75;

#declare Walthierite_IOR_e_1 = 1.604;
#declare Walthierite_IOR_w_1 = 1.588;
#declare Walthierite_Birefringence_1 = 0.0160;

#declare Wardite_IOR_e_1 = 1.607;
#declare Wardite_IOR_w_1 = 1.597;
#declare Wardite_Birefringence_1 = 0.0100;

#declare Wardsmithite_IOR_e_1 = 1.476;
#declare Wardsmithite_IOR_w_1 = 1.49;
#declare Wardsmithite_Birefringence_1 = 0.0140;

#declare Waylandite_IOR_e_1 = 1.748;
#declare Waylandite_IOR_w_1 = 1.774;
#declare Waylandite_Birefringence_1 = 0.0260;

#declare Weddellite_IOR_e_1 = 1.544;
#declare Weddellite_IOR_w_1 = 1.523;
#declare Weddellite_Birefringence_1 = 0.0210;

#declare Weilerite_IOR_e_1 = 1.688;
#declare Weilerite_IOR_w_1 = 1.698;
#declare Weilerite_Birefringence_1 = 0.0100;

#declare Welinite_III_IOR_e_1 = 1.88;
#declare Welinite_III_IOR_w_1 = 1.864;
#declare Welinite_III_Birefringence_1 = 0.0160;

#declare Welinite_VIII_IOR_e_1 = 1.88;
#declare Welinite_VIII_IOR_w_1 = 1.864;
#declare Welinite_VIII_Birefringence_1 = 0.0160;

#declare Wenkite_IOR_e_1 = 1.589;
#declare Wenkite_IOR_w_1 = 1.596;
#declare Wenkite_Birefringence_1 = 0.0070;

#declare Wermlandite_IOR_e_1 = 1.482;
#declare Wermlandite_IOR_w_1 = 1.493;
#declare Wermlandite_Birefringence_1 = 0.0110;

#declare Wesselsite_IOR_e_1 = 1.59;
#declare Wesselsite_IOR_w_1 = 1.63;
#declare Wesselsite_Birefringence_1 = 0.0400;

#declare Whitlockite_IOR_e_1 = 1.626;
#declare Whitlockite_IOR_w_1 = 1.629;
#declare Whitlockite_Birefringence_1 = 0.0030;

#declare Wickenburgite_IOR_e_1 = 1.648;
#declare Wickenburgite_IOR_w_1 = 1.6918;
#declare Wickenburgite_Birefringence_1 = 0.0438;

#declare Wilkeite_IOR_e_1 = 1.65;

#declare Willemite_IOR_e_1 = 1.719;
#declare Willemite_IOR_e_2 = 1.73;
#declare Willemite_IOR_w_1 = 1.691;
#declare Willemite_IOR_w_2 = 1.72;
#declare Willemite_Birefringence_1 = 0.0100;
#declare Willemite_Birefringence_2 = 0.0280;

#declare Wiserite_IOR_e_1 = 1.7;
#declare Wiserite_IOR_e_2 = 1.717;
#declare Wiserite_IOR_w_1 = 1.751;
#declare Wiserite_IOR_w_2 = 1.76;
#declare Wiserite_Birefringence_1 = 0.0430;
#declare Wiserite_Birefringence_2 = 0.0510;

#declare Woodhouseite_IOR_e_1 = 1.647;
#declare Woodhouseite_IOR_w_1 = 1.636;
#declare Woodhouseite_Birefringence_1 = 0.0110;

#declare Wulfenite_IOR_e_1 = 2.304;
#declare Wulfenite_IOR_w_1 = 2.402;
#declare Wulfenite_Birefringence_1 = 0.0980;

#declare Wurtzite_IOR_w_1 = 2.5;

#declare Xenotime_Y_IOR_e_1 = 1.815;
#declare Xenotime_Y_IOR_w_1 = 1.72;
#declare Xenotime_Y_Birefringence_1 = 0.0950;

#declare Yagiite_IOR_e_1 = 1.544;
#declare Yagiite_IOR_w_1 = 1.536;
#declare Yagiite_Birefringence_1 = 0.0080;

#declare Yecoraite_IOR_e_1 = 1.824;
#declare Yecoraite_IOR_w_1 = 1.812;
#declare Yecoraite_Birefringence_1 = 0.0120;

#declare Yedlinite_IOR_e_1 = 2.059;
#declare Yedlinite_IOR_w_1 = 2.125;
#declare Yedlinite_Birefringence_1 = 0.0660;

#declare Yoshiokaite_IOR_e_1 = 1.62;
#declare Yoshiokaite_IOR_e_2 = 1.64;
#declare Yoshiokaite_IOR_w_1 = 1.56;
#declare Yoshiokaite_IOR_w_2 = 1.58;
#declare Yoshiokaite_Birefringence_1 = 0.0600;

#declare Zairite_IOR_e_1 = 1.81;
#declare Zairite_IOR_w_1 = 1.82;
#declare Zairite_IOR_w_2 = 1.83;
#declare Zairite_Birefringence_1 = 0.0100;
#declare Zairite_Birefringence_2 = 0.0200;

#declare Zajacite_Ce_IOR_e_1 = 1.503;
#declare Zajacite_Ce_IOR_w_1 = 1.483;
#declare Zajacite_Ce_Birefringence_1 = 0.0200;

#declare Zakharovite_IOR_e_1 = 1.535;
#declare Zakharovite_IOR_w_1 = 1.565;
#declare Zakharovite_Birefringence_1 = 0.0300;

#declare Zapatalite_IOR_e_1 = 1.635;
#declare Zapatalite_IOR_w_1 = 1.646;
#declare Zapatalite_Birefringence_1 = 0.0110;

#declare Zavaritskite_IOR_a_1 = 2.21;
#declare Zavaritskite_IOR_b_1 = 2.213;
#declare Zavaritskite_Birefringence_1 = 0.0030;

#declare Zdenekite_IOR_e_1 = 1.71;
#declare Zdenekite_IOR_w_1 = 1.77;
#declare Zdenekite_Birefringence_1 = 0.0600;

#declare Zemannite_IOR_e_1 = 1.93;
#declare Zemannite_IOR_w_1 = 1.85;
#declare Zemannite_Birefringence_1 = 0.0800;

#declare Zemkorite_IOR_e_1 = 1.513;
#declare Zemkorite_IOR_w_1 = 1.535;
#declare Zemkorite_Birefringence_1 = 0.0220;

#declare Zeunerite_IOR_e_1 = 1.576;
#declare Zeunerite_IOR_e_2 = 1.623;
#declare Zeunerite_IOR_w_1 = 1.585;
#declare Zeunerite_IOR_w_2 = 1.643;
#declare Zeunerite_Birefringence_1 = 0.0090;
#declare Zeunerite_Birefringence_2 = 0.0200;

#declare Zhemchuzhnikovite_IOR_e_1 = 1.408;
#declare Zhemchuzhnikovite_IOR_w_1 = 1.479;
#declare Zhemchuzhnikovite_Birefringence_1 = 0.0710;

#declare Zhonghuacerite_Ce_IOR_e_1 = 1.565;
#declare Zhonghuacerite_Ce_IOR_w_1 = 1.745;
#declare Zhonghuacerite_Ce_Birefringence_1 = 0.1800;

#declare Zincaluminite_IOR_e_1 = 1.514;
#declare Zincaluminite_IOR_w_1 = 1.534;
#declare Zincaluminite_Birefringence_1 = 0.0200;

#declare Zincite_IOR_e_1 = 2.029;
#declare Zincite_IOR_w_1 = 2.013;
#declare Zincite_Birefringence_1 = 0.0160;

#declare Zincohogbomite_IOR_e_1 = 1.832;
#declare Zincohogbomite_IOR_w_1 = 1.878;
#declare Zincohogbomite_Birefringence_1 = 0.0460;

#declare Zircon_IOR_e_1 = 1.92;
#declare Zircon_IOR_e_2 = 1.96;
#declare Zircon_IOR_w_1 = 1.967;
#declare Zircon_IOR_w_2 = 2.015;
#declare Zircon_Birefringence_1 = 0.0470;
#declare Zircon_Birefringence_2 = 0.0550;

#declare Zirklerite_IOR_e_1 = 1.552;
#declare Zirklerite_IOR_w_1 = 1.522;
#declare Zirklerite_Birefringence_1 = 0.0300;

#declare Zirsinalite_IOR_e_1 = 1.605;
#declare Zirsinalite_IOR_w_1 = 1.61;
#declare Zirsinalite_Birefringence_1 = 0.0050;

#declare Zussmanite_IOR_e_1 = 1.623;
#declare Zussmanite_IOR_w_1 = 1.643;
#declare Zussmanite_Birefringence_1 = 0.0200;

#ifdef(View_POV_Include_Stack)
    #debug "    ...done!\n"
#end

// END OF FILE IOR_Uniaxial.inc
