#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Misc.inc\n"
#end
/////////////////////////////////////////////////
//                    MISC.                    //
/////////////////////////////////////////////////
#declare Bariumdifluorid_IOR = 1.470; // BaF2
#declare Birusa_1_IOR = 1.650; // Bright blue and green
#declare Birusa_2_IOR = 1.620; // The name have been transcribed from Russian. Anyone knows its English name?
#declare Birusa_3_IOR = 1.610; //
#declare Calciumdifluorid_IOR = 1.430; // CaF2
#declare Calspar_1_IOR = 1.660;
#declare Calspar_2_IOR = 1.486;
#declare Iodine_Crystal_IOR = 3.340;
#declare Lithiumfluoride_IOR = 1.390; // LiF
#declare Magnesium_oxide_IOR = 1.700; // MgO. Ionic crystal.
#declare Magnesiumdifluorid_IOR = 1.380; // MgF2
#declare Potassium_di_H_orthophosphate_IOR = 1.500; // KH2PO4
#declare Potassiumbromide_IOR = 1.560; // KBr
#declare Potassiumfluorid_IOR = 1.360; // KF
#declare Silvin_IOR = 1.490; // (KCl) colorless
#declare Sodiumbromide_IOR = 1.640; // NaBr
#declare Strontiumdifluorid_IOR = 1.440; // SrF2
#declare Tooth_structure_enamel_IOR = 1.655;
#declare Zinc_sulfide_IOR = 2.400; // ZnS. Common name is zinc blende. Ionic crystal having a beautiful redish yellow color.

//
// Ophthalmic materials, plastics
// Source: https://en.wikipedia.org/wiki/Corrective_lens#Ophthalmic_material_property_tables
//
#declare CR-39_Hard_Resin_IOR = 1.49;
#declare PPG_Trivex_(Average)_IOR = 1.53;
#declare SOLA_Spectralite_IOR = 1.54;
#declare Essilor_Ormix_IOR = 1.6;
#declare Polycarbonate_IOR = 1.586;
#declare MR-8_1.6_Plastic_IOR = 1.6;
#declare MR-6_1.6_Plastic_IOR = 1.6;
#declare MR-20_1.6_Plastic_IOR = 1.60;
#declare SOLA_Finalite_IOR = 1.60;
#declare MR-7_1.665_Plastic_IOR = 1.665;
#declare MR-7_1.67_Plastic_IOR = 1.67;
#declare MR-10_1.67_Plastic_IOR = 1.67;
#declare Nikon_4_Plastic_NL4_IOR = 1.67;
#declare Hoya_EYRY_IOR = 1.70;
#declare MR-174_1.74_Plastic_IOR = 1.74;
#declare Nikon_5_Plastic_NL5_IOR = 1.74;
#declare Tokai_IOR = 1.76;

//
// Ophthalmic materials, glass
// Source: https://en.wikipedia.org/wiki/Corrective_lens#Ophthalmic_material_property_tables
//
#declare Crown_Glass_IOR = 1.525;
#declare PhotoGray_Extra_IOR = 1.523;
#declare 1.6_Glass_IOR = 1.604;
#declare 1.7_Glass_IOR = 1.706;
#declare 1.8_Glass_IOR = 1.800;
#declare 1.9_Glass_IOR = 1.893;


#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Misq.inc\n"
#end

// END OF FILE IOR_Misc.inc
