#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Liquids.inc\n"
#end
/////////////////////////////////////////////////
//                   LIQUIDS                   //
/////////////////////////////////////////////////
#declare Acetone_IOR_n_1 = 1.360;
#declare Alcohol_IOR_n_1 = 1.329; // Ethanol, C2H5OH
#declare Asphalt_IOR_n_1 = 1.635; // The hydro-carbon, not the road-asphalt :)
#declare Benzen_IOR_n_1 = 1.500;
#declare Canada_balsam_IOR_n_1 = 1.530; // Used as glue for optics.
#declare Carbon_tetrachloride_IOR_n_1 = 1.460; // Provided by Sigmund Kyrre Aas <as@stud.ntnu.no>
#declare Carbondisulfide_IOR_n_1 = 1.630;
#declare Ethyl_Alcohol_IOR_n_1 = 1.360;
#declare Flourite_IOR_n_1 = 1.434;
#declare Glycerine_IOR_n_1 = 1.473; // Provided by Sigmund Kyrre Aas <as@stud.ntnu.no>
#declare Liquid_CarbonDioxide_IOR_n_1 = 1.20;
#declare Sugar_Solution_30_IOR_n_1 = 1.380; // 30% solution
#declare Sugar_Solution_80_IOR_n_1 = 1.490; // 80% solution
#declare Terpentine_IOR_n_1 = 1.427; // Provided by Sigmund Kyrre Aas <as@stud.ntnu.no>
#declare Water_20_C_IOR_n_1 = 1.333; // 20 degrees Celsius STP

#ifdef(View_POV_Include_Stack)
    #debug "    ...done!\n"
#end

// END OF FILE IOR_Liquids.inc
