#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Gases.inc\n"
#end

/////////////////////////////////////////////////
//                    GASES                    //
/////////////////////////////////////////////////
#declare IOR_Gas_Acetone = 1.00109; // Real name: Gas. Acetone. Source: [52]
#declare IOR_Gas_Air_at_0C = 1.000292; // Real name: Gas. Air at 0°C. Source: [21]. Comment: At 0°C
#declare IOR_Gas_Air_at_15C = 1.000277; // Real name: Gas. Air at 15°C. Source: [21]. Comment: At 15°C
#declare IOR_Gas_Air_at_15C = 1.000309; // Real name: Gas. Air at -15°C. Source: [21]. Comment: At -15°C
#declare IOR_Gas_Air_at_25C = 1.000277; // Real name: Gas. Air at 25°C. Source: [16]. Comment: At 25°C and 1 atm
#declare IOR_Gas_Air_at_30C = 1.000263; // Real name: Gas. Air at 30°C. Source: [21]. Comment: At 30°C
#declare IOR_Gas_Air_at_60C = 1.00024; // Real name: Gas. Air at 60°C. Source: [21]. Comment: At 60°C
#declare IOR_Gas_Alcohol_Methyl = 1.000586; // Real name: Gas. Alcohol Methyl. Source: [52]
#declare IOR_Gas_Ammonia = 1.000376; // Real name: Gas. Ammonia. Source: [52]
#declare IOR_Gas_Argon = 1.000281; // Real name: Gas. Argon. Source: [52]
#declare IOR_Gas_Benzene = 1.001762; // Real name: Gas. Benzene. Source: [52]
#declare IOR_Gas_Bromine = 1.001132; // Real name: Gas. Bromine. Source: [52]
#declare IOR_Gas_Carbon_Dioxide = 1.001; // Real name: Gas. Carbon Dioxide. Source: [52]
#declare IOR_Gas_Carbon_disulphide = 1.001481; // Real name: Gas. Carbon disulphide. Source: [52]
#declare IOR_Gas_Carbon_Monoxide = 1.000338; // Real name: Gas. Carbon Monoxide. Source: [52]
#declare IOR_Gas_Chlorine = 1.000773; // Real name: Gas. Chlorine. Source: [52]
#declare IOR_Gas_Chloroform = 1.00145; // Real name: Gas. Chloroform. Source: [52]
#declare IOR_Gas_Disilane = 1.001657; // Real name: Gas. Disilane. Source: [78]. Comment: Si2H6. at 0°C
#declare IOR_Gas_Ether_Ethyl = 1.001533; // Real name: Gas. Ether Ethyl. Source: [52]
#declare IOR_Gas_Ether_Methyl = 1.000891; // Real name: Gas. Ether Methyl. Source: [52]
#declare IOR_Gas_Ethyl_Alcohol = 1.000878; // Real name: Gas. Ethyl Alcohol. Source: [52]
#declare IOR_Gas_Helium = 1.000036; // Real name: Gas. Helium. Source: [52]. Comment: At 0°C
#declare IOR_Gas_Hydrochloric_Acid = 1.000447; // Real name: Gas. Hydrochloric Acid. Source: [52]
#declare IOR_Gas_Hydrogen = 1.000132; // Real name: Gas. Hydrogen. Source: [52]. Comment: At 0°C
#declare IOR_Gas_Methane = 1.000444; // Real name: Gas. Methane. Source: [52]
#declare IOR_Gas_Nitric_Oxide = 1.000297; // Real name: Gas. Nitric Oxide. Source: [52]
#declare IOR_Gas_Nitrogen = 1.000298; // Real name: Gas. Nitrogen. Source: [52]
#declare IOR_Gas_Nitrous_Oxide = 1.000516; // Real name: Gas. Nitrous Oxide. Source: [52]
#declare IOR_Gas_Oxygene = 1.000271; // Real name: Gas. Oxygene. Source: [52]
#declare IOR_Gas_Pentane = 1.000686; // Real name: Gas. Pentane. Source: [52]
#declare IOR_Gas_Perfluoro_n_butane = 1.0014; // Real name: Gas. Perfluoro-n-butane. Source: [50]. Comment: C4F10
#declare IOR_Gas_Sulphur_Dioxide = 1.000686; // Real name: Gas. Sulphur Dioxide. Source: [52]
#declare IOR_Gas_Water_vapor = 1.000261; // Real name: Gas. Water vapor. Source: [52]


#ifdef(View_POV_Include_Stack)
    #debug "    ...done!\n"
#end

// END OF FILE IOR_Gases.inc
