#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Liquids.inc\n"
#end
/////////////////////////////////////////////////
//                   LIQUIDS                   //
/////////////////////////////////////////////////
#declare 1_1_2_Trichlorotrifluoroethane_IOR = 1.3557; // At 25 degrees Celsius
#declare 1_2_4_Trichlorobenzene = 1.5717; // Solvent
#declare 1_4_Dioxane_IOR = 1.4224; // Solvent
#declare 2_Methoxyethanol_IOR = 1.4021; // Solvent
#declare Acetone_IOR = 1.3586; // Solvent
#declare Acetonitrile_IOR = 1.3441; // Solvent
#declare Asphalt_IOR = 1.635; // The hydro-carbon, bitumen, alse seen values 1.64 - 1.66
#declare Benzen_IOR = 1.500;
#declare Canada_balsam_IOR = 1.530; // Used as glue for optics.
#declare Carbon_tetrachloride_IOR = 1.460; // Provided by Sigmund Kyrre Aas
#declare Carbondisulfide_IOR = 1.630;
#declare Chlorobenzene_IOR = 1.5248; // Solvent
#declare Chloroform_IOR = 1.4458; // Solvent
#declare Cyclohexane_IOR = 1.4262; // Solvent
#declare Cyclopentane_IOR = 1.4064; // Solvent
#declare Dichloromethane_IOR = 1.4241; // Solvent
#declare Dimethyl_Acetamide_IOR = 1.4384; // Solvent
#declare Dimethyl_Sulfoxide_IOR = 1.4793; // Solvent
#declare Ethyl_Acetate_IOR = 1.3724; // Solvent
#declare Ethyl_Alcohol_1_IOR = 1.329; // Ethanol/Ethyl Alcohol, C2H5OH
#declare Ethyl_Alcohol_2_IOR = 1.360; // Ethanol/Ethyl Alcohol, C2H5OH
#declare Ethyl_Alcohol_3_IOR = 1.3614; // Solvent, Ethanol/Ethyl Alcohol, C2H5OH
#declare Ethyl_Ether_IOR = 1.3524; // Solvent
#declare Ethylene_Dichloride_IOR = 1.4448; // Solvent
#declare Flourite_IOR = 1.434;
#declare Glycerine_IOR = 1.473; // Provided by Sigmund Kyrre Aas
#declare Glyme_IOR = 1.3796; // Solvent
#declare Heptane_IOR = 1.3876; // Solvent
#declare Hexane_IOR = 1.3749; // Solvent
#declare Iso_Octane_IOR = 1.3914; // Solvent
#declare Isobutyl_Alcohol_IOR = 1.3959; // Solvent
#declare Isopropyl_Alcohol_IOR = 1.3772; // Solvent
#declare Isopropyl_Myristate_IOR = 1.4332; // Solvent
#declare Liquid_CarbonDioxide_IOR = 1.20;
#declare Methanol_IOR = 1.3284; // Solvent
#declare Methyl_Ethyl_Ketone_IOR = 1.3788; // Solvent
#declare Methyl_Isoamyl_Ketone_IOR = 1.4070; // Solvent
#declare Methyl_Isobutyl_Ketone_IOR = 1.3957; // Solvent
#declare Methyl_n_Propyl_Ketone_IOR = 1.3901; // Solvent
#declare Methyl_t_Butyl_Ether_IOR = 1.3689; // Solvent
#declare n_Butyl_Acetate_IOR = 1.3942; // Solvent
#declare n_Butyl_Alcohol_IOR = 1.3993; // Solvent
#declare n_Butyl_Chloride_IOR = 1.4021; // Solvent
#declare N_Methylpyrrolidone_IOR = 1.4700; // Solvent
#declare N_N_Dimethylformamide_IOR = 1.4305; // Solvent
#declare n_Propyl_Alcohol_IOR = 1.3856; // Solvent
#declare o_Dichlorobenzene_IOR = 1.5514; // Solvent
#declare o_Xylene_IOR = 1.5054; // Solvent
#declare Pentane_IOR = 1.3575; // Solvent
#declare Petroleum_Ether_IOR = 1.3650; // Solvent
#declare Propylene_Carbonate_IOR = 1.4210; // Solvent
#declare Pyridine_IOR = 1.5102; // Solvent
#declare Sugar_Solution_30_IOR = 1.380; // 30% solution
#declare Sugar_Solution_80_IOR = 1.490; // 80% solution
#declare Terpentine_IOR = 1.427; // Provided by Sigmund Kyrre Aas
#declare Tetrahydrofuran_IOR = 1.4072; // Solvent
#declare Toluene_IOR = 1.4969; // Solvent
#declare Triethylamine_IOR = 1.4010; // Solvent
#declare Trifluoroacetic_Acid_IOR = 1.2850; // Solvent
#declare Water_20_C_IOR = 1.333; // 20 degrees Celsius STP


#ifdef(View_POV_Include_Stack)
    #debug "    ...done!\n"
#end

// END OF FILE IOR_Liquids.inc
