#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Dispersion.inc\n"
#end
/////////////////////////////////////////////////
//                 DISPERSION                  //
/////////////////////////////////////////////////

#declare Dispersion_Base = 1.000; // MegaPOV uses 1 to mean no dispersion.

Almandite_Dispersion = 0.024 + Dispersion_Base;
Andradite_Dispersion = 0.057 + Dispersion_Base;
Benitoite_Dispersion = 0.044 + Dispersion_Base;
Beryl_Dispersion = 0.014 + Dispersion_Base;
Beryllonite_Dispersion = 0.010 + Dispersion_Base;
Cassiterite_Dispersion = 0.071 + Dispersion_Base;
Chrysoberyl_Dispersion = 0.015 + Dispersion_Base;
Corundum_Dispersion = 0.018 + Dispersion_Base;
Danburite_Dispersion = 0.016 + Dispersion_Base;
Datolite_Dispersion = 0.016 + Dispersion_Base;
Diamond_Dispersion = 0.044 + Dispersion_Base;
Dioptase_Dispersion = 0.022 + Dispersion_Base;
Epidote_Dispersion = 0.030 + Dispersion_Base;
Euclase_Dispersion = 0.016 + Dispersion_Base;
Fluorite_Dispersion = 0.007 + Dispersion_Base;
Grossularite_Dispersion = 0.028 + Dispersion_Base;
Idocrase_Dispersion = 0.019 + Dispersion_Base;
Kornerupine_Dispersion = 0.019 + Dispersion_Base;
Kyanite_Dispersion = 0.011 + Dispersion_Base;
Orthoclase_Dispersion = 0.012 + Dispersion_Base;
Peridot_Dispersion = 0.020 + Dispersion_Base;
Phenakite_Dispersion = 0.015 + Dispersion_Base;
Pyrope_Dispersion = 0.027 + Dispersion_Base;
Quartz_Dispersion = 0.013 + Dispersion_Base;
Rhodolite_Dispersion = 0.026 + Dispersion_Base;
Rutile_Synthetic_Dispersion = 0.330 + Dispersion_Base;
Scapolite_Dispersion = 0.017 + Dispersion_Base;
Silica_glass_Dispersion = 0.010 + Dispersion_Base;
Sillimanite_Dispersion = 0.015 + Dispersion_Base;
Spessartite_Dispersion = 0.027 + Dispersion_Base;
Sphalerite_Dispersion = 0.156 + Dispersion_Base;
Sphene_Dispersion = 0.051 + Dispersion_Base;
Spinel_Dispersion = 0.020 + Dispersion_Base;
Spodumene_Dispersion = 0.017 + Dispersion_Base;
Strontium titanate_Dispersion = 0.109 + Dispersion_Base;
Topaz_Dispersion = 0.014 + Dispersion_Base;
Tourmaline_Dispersion = 0.017 + Dispersion_Base;
Zircon_Dispersion = 0.038 + Dispersion_Base;


#ifdef(View_POV_Include_Stack)
    #debug "    ...done!\n"
#end

// END OF FILE IOR_Dispersion.inc
