#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Misc.inc\n"
#end
/////////////////////////////////////////////////
//                    MISC.                    //
/////////////////////////////////////////////////
#declare Bariumdifluorid_IOR = 1.470; // BaF2
#declare Birusa_1_IOR = 1.650; // Bright blue and green
#declare Birusa_2_IOR = 1.620; // The name have been transcribed from Russian. Anyone knows its English name?
#declare Birusa_3_IOR = 1.610; //
#declare Calciumdifluorid_IOR = 1.430; // CaF2
#declare Calspar_1_IOR = 1.660;
#declare Calspar_2_IOR = 1.486;
#declare Iodine_Crystal_IOR = 3.340;
#declare Lithiumfluoride_IOR = 1.390; // LiF
#declare Magnesium_oxide_IOR = 1.700; // MgO. Ionic crystal.
#declare Magnesiumdifluorid_IOR = 1.380; // MgF2
#declare Potassium_di_H_orthophosphate_IOR = 1.500; // KH2PO4
#declare Potassiumbromide_IOR = 1.560; // KBr
#declare Potassiumfluorid_IOR = 1.360; // KF
#declare Silvin_IOR = 1.490; // (KCl) colorless
#declare Sodiumbromide_IOR = 1.640; // NaBr
#declare Strontiumdifluorid_IOR = 1.440; // SrF2
#declare Tooth_structure_enamel_IOR = 1.655;
#declare Zinc_sulfide_IOR = 2.400; // ZnS. Common name is zinc blende. Ionic crystal having a beautiful redish yellow color.


#ifdef(View_POV_Include_Stack)
    #debug "  - including IOR_Misq.inc\n"
#end

// END OF FILE IOR_Misc.inc
